// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ClickTwice.Publisher.Core.Resources
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\alist\Source\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class LaunchPage : LaunchPageBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n<!DOCTYPE HTML>\r\n<!--\r\n\tEventually by HTML5 UP\r\n\t\r\n\tFree for personal and comme" +
                    "rcial use under the CCA 3.0 license (html5up.net/license)\r\n-->\r\n<html>\r\n<head>\r\n" +
                    "\t<title>");
            
            #line 16 "C:\Users\alist\Source\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Manifest.ApplicationName));
            
            #line default
            #line hidden
            this.Write("</title>\r\n\t<meta charset=\"utf-8\" />\r\n\t<meta name=\"viewport\" content=\"width=device" +
                    "-width, initial-scale=1, user-scalable=no\" />\r\n\t<!-- <link rel=\"stylesheet\" href" +
                    "=\"assets/css/main.css\"/> -->\r\n\t<link rel=\"stylesheet\" href=\"https://maxcdn.boots" +
                    "trapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\" />\r\n\t<style>\r\n\t@import " +
                    "url(\"http://fonts.googleapis.com/css?family=Roboto:400,700\");\r\n\r\n/*\r\n\tEventually" +
                    " by HTML5 UP\r\n\thtml5up.net | @n33co\r\n\tFree for personal and commercial use under" +
                    " the CCA 3.0 license (html5up.net/license)\r\n*/\r\n\r\n\r\n/* Reset */\r\n\r\nhtml,\r\nbody,\r" +
                    "\ndiv,\r\nspan,\r\napplet,\r\nobject,\r\niframe,\r\nh1,\r\nh2,\r\nh3,\r\nh4,\r\nh5,\r\nh6,\r\np,\r\nblock" +
                    "quote,\r\npre,\r\na,\r\nabbr,\r\nacronym,\r\naddress,\r\nbig,\r\ncite,\r\ncode,\r\ndel,\r\ndfn,\r\nem," +
                    "\r\nimg,\r\nins,\r\nkbd,\r\nq,\r\ns,\r\nsamp,\r\nsmall,\r\nstrike,\r\nstrong,\r\nsub,\r\nsup,\r\ntt,\r\nva" +
                    "r,\r\nb,\r\nu,\r\ni,\r\ncenter,\r\ndl,\r\ndt,\r\ndd,\r\nol,\r\nul,\r\nli,\r\nfieldset,\r\nform,\r\nlabel,\r" +
                    "\nlegend,\r\ntable,\r\ncaption,\r\ntbody,\r\ntfoot,\r\nthead,\r\ntr,\r\nth,\r\ntd,\r\narticle,\r\nasi" +
                    "de,\r\ncanvas,\r\ndetails,\r\nembed,\r\nfigure,\r\nfigcaption,\r\nfooter,\r\nheader,\r\nhgroup,\r" +
                    "\nmenu,\r\nnav,\r\noutput,\r\nruby,\r\nsection,\r\nsummary,\r\ntime,\r\nmark,\r\naudio,\r\nvideo {\r" +
                    "\n    margin: 0;\r\n    padding: 0;\r\n    border: 0;\r\n    font-size: 100%;\r\n    font" +
                    ": inherit;\r\n    vertical-align: baseline;\r\n}\r\n\r\narticle,\r\naside,\r\ndetails,\r\nfigc" +
                    "aption,\r\nfigure,\r\nfooter,\r\nheader,\r\nhgroup,\r\nmenu,\r\nnav,\r\nsection {\r\n    display" +
                    ": block;\r\n}\r\n\r\nbody {\r\n    line-height: 1;\r\n}\r\n\r\nol,\r\nul {\r\n    list-style: none" +
                    ";\r\n}\r\n\r\nblockquote,\r\nq {\r\n    quotes: none;\r\n}\r\n\r\nblockquote:before,\r\nblockquote" +
                    ":after,\r\nq:before,\r\nq:after {\r\n    content: \'\';\r\n    content: none;\r\n}\r\n\r\ntable " +
                    "{\r\n    border-collapse: collapse;\r\n    border-spacing: 0;\r\n}\r\n\r\nbody {\r\n    -web" +
                    "kit-text-size-adjust: none;\r\n}\r\n\r\n\r\n/* Box Model */\r\n\r\n*,\r\n*:before,\r\n*:after {\r" +
                    "\n    -moz-box-sizing: border-box;\r\n    -webkit-box-sizing: border-box;\r\n    box-" +
                    "sizing: border-box;\r\n}\r\n\r\n\r\n/* Basic */\r\n\r\n@-ms-viewport {\r\n    width: device-wi" +
                    "dth;\r\n}\r\n\r\nbody {\r\n    -ms-overflow-style: scrollbar;\r\n}\r\n\r\n@media screen and (m" +
                    "ax-width: 480px) {\r\n    html,\r\n    body {\r\n        min-width: 320px;\r\n    }\r\n}\r\n" +
                    "\r\nhtml,\r\nbody {\r\n    height: 100%;\r\n    overflow-x: hidden;\r\n    width: 100%;\r\n}" +
                    "\r\n\r\n@media screen and (max-height: 640px) {\r\n    html,\r\n    body {\r\n        heig" +
                    "ht: auto;\r\n        min-height: 100%;\r\n    }\r\n}\r\n\r\nbody {\r\n    display: -moz-flex" +
                    ";\r\n    display: -webkit-flex;\r\n    display: -ms-flex;\r\n    display: flex;\r\n    -" +
                    "moz-flex-direction: column;\r\n    -webkit-flex-direction: column;\r\n    -ms-flex-d" +
                    "irection: column;\r\n    flex-direction: column;\r\n    -moz-justify-content: center" +
                    ";\r\n    -webkit-justify-content: center;\r\n    -ms-justify-content: center;\r\n    j" +
                    "ustify-content: center;\r\n    background-color: #000;\r\n    padding: 6em 4em 4em 4" +
                    "em;\r\n}\r\n\r\nbody > * {\r\n    position: relative;\r\n    z-index: 2;\r\n}\r\n\r\nbody.is-loa" +
                    "ding *,\r\nbody.is-loading *:before,\r\nbody.is-loading *:after {\r\n    -moz-animatio" +
                    "n: none !important;\r\n    -webkit-animation: none !important;\r\n    -ms-animation:" +
                    " none !important;\r\n    animation: none !important;\r\n    -moz-transition: none !i" +
                    "mportant;\r\n    -webkit-transition: none !important;\r\n    -ms-transition: none !i" +
                    "mportant;\r\n    transition: none !important;\r\n}\r\n\r\n@media screen and (max-width: " +
                    "1680px) {\r\n    body {\r\n        padding: 6em 3.5em 3.5em 3.5em;\r\n    }\r\n}\r\n\r\n@med" +
                    "ia screen and (max-width: 736px) {\r\n    body {\r\n        padding: 5em 2em 2em 2em" +
                    ";\r\n    }\r\n}\r\n\r\n@media screen and (max-width: 360px) {\r\n    body {\r\n        paddi" +
                    "ng: 5em 1.25em 1.25em 1.25em;\r\n    }\r\n}\r\n\r\n\r\n/* BG */\r\n\r\n#bg {\r\n    -moz-transit" +
                    "ion: opacity 2s ease-in-out;\r\n    -webkit-transition: opacity 2s ease-in-out;\r\n " +
                    "   -ms-transition: opacity 2s ease-in-out;\r\n    transition: opacity 2s ease-in-o" +
                    "ut;\r\n    height: 100%;\r\n    left: 0;\r\n    opacity: 0.25;\r\n    position: fixed;\r\n" +
                    "    top: 0;\r\n    width: 100%;\r\n    z-index: 1;\r\n}\r\n\r\n#bg div {\r\n    -moz-transit" +
                    "ion: opacity 3s ease, visibility 3s;\r\n    -webkit-transition: opacity 3s ease, v" +
                    "isibility 3s;\r\n    -ms-transition: opacity 3s ease, visibility 3s;\r\n    transiti" +
                    "on: opacity 3s ease, visibility 3s;\r\n    background-size: cover;\r\n    height: 10" +
                    "0%;\r\n    left: 0;\r\n    opacity: 0;\r\n    position: absolute;\r\n    top: 0;\r\n    vi" +
                    "sibility: hidden;\r\n    width: 150%;\r\n}\r\n\r\n#bg div.visible {\r\n    -moz-animation:" +
                    " bg 45s linear infinite;\r\n    -webkit-animation: bg 45s linear infinite;\r\n    -m" +
                    "s-animation: bg 45s linear infinite;\r\n    animation: bg 45s linear infinite;\r\n  " +
                    "  opacity: 1;\r\n    visibility: visible;\r\n    z-index: 1;\r\n}\r\n\r\n#bg div.visible.t" +
                    "op {\r\n    z-index: 2;\r\n}\r\n\r\n@media screen and (max-width: 1280px) {\r\n    #bg div" +
                    ".visible {\r\n        -moz-animation: bg 29.25s linear infinite;\r\n        -webkit-" +
                    "animation: bg 29.25s linear infinite;\r\n        -ms-animation: bg 29.25s linear i" +
                    "nfinite;\r\n        animation: bg 29.25s linear infinite;\r\n    }\r\n}\r\n\r\n@media scre" +
                    "en and (max-width: 736px) {\r\n    #bg div.visible {\r\n        -moz-animation: bg 1" +
                    "8s linear infinite;\r\n        -webkit-animation: bg 18s linear infinite;\r\n       " +
                    " -ms-animation: bg 18s linear infinite;\r\n        animation: bg 18s linear infini" +
                    "te;\r\n    }\r\n}\r\n\r\n#bg div:only-child {\r\n    -moz-animation-direction: alternate !" +
                    "important;\r\n    -webkit-animation-direction: alternate !important;\r\n    -ms-anim" +
                    "ation-direction: alternate !important;\r\n    animation-direction: alternate !impo" +
                    "rtant;\r\n}\r\n\r\nbody.is-loading #bg {\r\n    opacity: 0;\r\n}\r\n\r\n@-moz-keyframes bg {\r\n" +
                    "    0% {\r\n        -moz-transform: translateX(0);\r\n        -webkit-transform: tra" +
                    "nslateX(0);\r\n        -ms-transform: translateX(0);\r\n        transform: translate" +
                    "X(0);\r\n    }\r\n    100% {\r\n        -moz-transform: translateX(-25%);\r\n        -we" +
                    "bkit-transform: translateX(-25%);\r\n        -ms-transform: translateX(-25%);\r\n   " +
                    "     transform: translateX(-25%);\r\n    }\r\n}\r\n\r\n@-webkit-keyframes bg {\r\n    0% {" +
                    "\r\n        -moz-transform: translateX(0);\r\n        -webkit-transform: translateX(" +
                    "0);\r\n        -ms-transform: translateX(0);\r\n        transform: translateX(0);\r\n " +
                    "   }\r\n    100% {\r\n        -moz-transform: translateX(-25%);\r\n        -webkit-tra" +
                    "nsform: translateX(-25%);\r\n        -ms-transform: translateX(-25%);\r\n        tra" +
                    "nsform: translateX(-25%);\r\n    }\r\n}\r\n\r\n@-ms-keyframes bg {\r\n    0% {\r\n        -m" +
                    "oz-transform: translateX(0);\r\n        -webkit-transform: translateX(0);\r\n       " +
                    " -ms-transform: translateX(0);\r\n        transform: translateX(0);\r\n    }\r\n    10" +
                    "0% {\r\n        -moz-transform: translateX(-25%);\r\n        -webkit-transform: tran" +
                    "slateX(-25%);\r\n        -ms-transform: translateX(-25%);\r\n        transform: tran" +
                    "slateX(-25%);\r\n    }\r\n}\r\n\r\n@keyframes bg {\r\n    0% {\r\n        -moz-transform: tr" +
                    "anslateX(0);\r\n        -webkit-transform: translateX(0);\r\n        -ms-transform: " +
                    "translateX(0);\r\n        transform: translateX(0);\r\n    }\r\n    100% {\r\n        -m" +
                    "oz-transform: translateX(-25%);\r\n        -webkit-transform: translateX(-25%);\r\n " +
                    "       -ms-transform: translateX(-25%);\r\n        transform: translateX(-25%);\r\n " +
                    "   }\r\n}\r\n\r\n\r\n/* Type */\r\n\r\nbody,\r\ninput,\r\nselect,\r\ntextarea {\r\n    color: rgba(2" +
                    "55, 255, 255, 0.75);\r\n    font-family: \"Roboto\", sans-serif;\r\n    font-size: 16p" +
                    "t;\r\n    font-weight: 400;\r\n    letter-spacing: -0.01em;\r\n    line-height: 1.65em" +
                    ";\r\n}\r\n\r\n@media screen and (max-width: 1680px) {\r\n    body,\r\n    input,\r\n    sele" +
                    "ct,\r\n    textarea {\r\n        font-size: 12pt;\r\n    }\r\n}\r\n\r\n@media screen and (ma" +
                    "x-width: 1280px) {\r\n    body,\r\n    input,\r\n    select,\r\n    textarea {\r\n        " +
                    "font-size: 11pt;\r\n    }\r\n}\r\n\r\n@media screen and (max-width: 980px) {\r\n    body,\r" +
                    "\n    input,\r\n    select,\r\n    textarea {\r\n        font-size: 12pt;\r\n    }\r\n}\r\n\r\n" +
                    "@media screen and (max-width: 736px) {\r\n    body,\r\n    input,\r\n    select,\r\n    " +
                    "textarea {\r\n        font-size: 12pt;\r\n    }\r\n}\r\n\r\n@media screen and (max-width: " +
                    "480px) {\r\n    body,\r\n    input,\r\n    select,\r\n    textarea {\r\n        font-size:" +
                    " 12pt;\r\n    }\r\n}\r\n\r\na {\r\n    -moz-transition: border-bottom-color 0.2s ease, col" +
                    "or 0.2s ease;\r\n    -webkit-transition: border-bottom-color 0.2s ease, color 0.2s" +
                    " ease;\r\n    -ms-transition: border-bottom-color 0.2s ease, color 0.2s ease;\r\n   " +
                    " transition: border-bottom-color 0.2s ease, color 0.2s ease;\r\n    border-bottom:" +
                    " dotted 1px rgba(255, 255, 255, 0.25);\r\n    color: #74B3CE;\r\n    text-decoration" +
                    ": none;\r\n}\r\n\r\na.install {\r\n    background-color: #413C58;\r\n}\r\n\r\na:hover {\r\n    b" +
                    "order-bottom-color: transparent;\r\n    color: #413C58 !important;\r\n    text-decor" +
                    "ation: none;\r\n}\r\n\r\nstrong,\r\nb {\r\n    color: #fff;\r\n    font-weight: 700;\r\n}\r\n\r\ne" +
                    "m,\r\ni {\r\n    font-style: italic;\r\n}\r\n\r\np {\r\n    margin: 0 0 2em 0;\r\n}\r\n\r\nh1,\r\nh2" +
                    ",\r\nh3,\r\nh4,\r\nh5,\r\nh6 {\r\n    color: #fff;\r\n    font-weight: 700;\r\n    line-height" +
                    ": 1em;\r\n    margin: 0 0 1em 0;\r\n}\r\n\r\nh1 a,\r\nh2 a,\r\nh3 a,\r\nh4 a,\r\nh5 a,\r\nh6 a {\r\n" +
                    "    color: inherit;\r\n    text-decoration: none;\r\n}\r\n\r\nh1 {\r\n    font-size: 2.5em" +
                    ";\r\n    line-height: 1.25em;\r\n}\r\n\r\nh2 {\r\n    font-size: 1.75em;\r\n    line-height:" +
                    " 1.5em;\r\n}\r\n\r\nh3 {\r\n    font-size: 1.35em;\r\n    line-height: 1.5em;\r\n}\r\n\r\nh4 {\r\n" +
                    "    font-size: 1.1em;\r\n    line-height: 1.5em;\r\n}\r\n\r\nh5 {\r\n    font-size: 0.9em;" +
                    "\r\n    line-height: 1.5em;\r\n}\r\n\r\nh6 {\r\n    font-size: 0.7em;\r\n    line-height: 1." +
                    "5em;\r\n}\r\n\r\nsub {\r\n    font-size: 0.8em;\r\n    position: relative;\r\n    top: 0.5em" +
                    ";\r\n}\r\n\r\nsup {\r\n    font-size: 0.8em;\r\n    position: relative;\r\n    top: -0.5em;\r" +
                    "\n}\r\n\r\nblockquote {\r\n    border-left: solid 8px rgba(255, 255, 255, 0.35);\r\n    f" +
                    "ont-style: italic;\r\n    margin: 0 0 2em 0;\r\n    padding: 0.5em 0 0.5em 2em;\r\n}\r\n" +
                    "\r\ncode {\r\n    background: rgba(255, 255, 255, 0.125);\r\n    border-radius: 6px;\r\n" +
                    "    border: solid 2px rgba(255, 255, 255, 0.35);\r\n    font-family: \"Courier New\"" +
                    ", monospace;\r\n    font-size: 0.9em;\r\n    margin: 0 0.25em;\r\n    padding: 0.25em " +
                    "0.65em;\r\n}\r\n\r\npre {\r\n    -webkit-overflow-scrolling: touch;\r\n    font-family: \"C" +
                    "ourier New\", monospace;\r\n    font-size: 0.9em;\r\n    margin: 0 0 2em 0;\r\n}\r\n\r\npre" +
                    " code {\r\n    display: block;\r\n    line-height: 1.75em;\r\n    padding: 1em 1.5em;\r" +
                    "\n    overflow-x: auto;\r\n}\r\n\r\nhr {\r\n    border: 0;\r\n    border-bottom: solid 2px " +
                    "rgba(255, 255, 255, 0.35);\r\n    margin: 2em 0;\r\n}\r\n\r\nhr.major {\r\n    margin: 3em" +
                    " 0;\r\n}\r\n\r\n\r\n/* Section/Article */\r\n\r\nsection.special,\r\narticle.special {\r\n    te" +
                    "xt-align: center;\r\n}\r\n\r\nheader p {\r\n    color: rgba(255, 255, 255, 0.5);\r\n    po" +
                    "sition: relative;\r\n    margin: 0 0 1.5em 0;\r\n}\r\n\r\nheader h2 + p {\r\n    font-size" +
                    ": 1.25em;\r\n    margin-top: -1em;\r\n    line-height: 1.5em;\r\n}\r\n\r\nheader h3 + p {\r" +
                    "\n    font-size: 1.1em;\r\n    margin-top: -0.8em;\r\n    line-height: 1.5em;\r\n}\r\n\r\nh" +
                    "eader h4 + p,\r\nheader h5 + p,\r\nheader h6 + p {\r\n    font-size: 0.9em;\r\n    margi" +
                    "n-top: -0.6em;\r\n    line-height: 1.5em;\r\n}\r\n\r\n@media screen and (max-width: 980p" +
                    "x) {\r\n    header br {\r\n        display: none;\r\n    }\r\n}\r\n\r\n@media screen and (ma" +
                    "x-width: 736px) {\r\n    header br {\r\n        display: inline;\r\n    }\r\n}\r\n\r\n@media" +
                    " screen and (max-width: 480px) {\r\n    header br {\r\n        display: none;\r\n    }" +
                    "\r\n}\r\n\r\n\r\n/* Icon */\r\n\r\n.icon {\r\n    text-decoration: none;\r\n    border-bottom: n" +
                    "one;\r\n    position: relative;\r\n}\r\n\r\n.icon:before {\r\n    -moz-osx-font-smoothing:" +
                    " grayscale;\r\n    -webkit-font-smoothing: antialiased;\r\n    font-family: FontAwes" +
                    "ome;\r\n    font-style: normal;\r\n    font-weight: normal;\r\n    text-transform: non" +
                    "e !important;\r\n}\r\n\r\n.icon > .label {\r\n    display: none;\r\n}\r\n\r\n\r\n/* List */\r\n\r\no" +
                    "l {\r\n    list-style: decimal;\r\n    margin: 0 0 2em 0;\r\n    padding-left: 1.25em;" +
                    "\r\n}\r\n\r\nol li {\r\n    padding-left: 0.25em;\r\n}\r\n\r\nul {\r\n    list-style: disc;\r\n   " +
                    " margin: 0 0 2em 0;\r\n    padding-left: 1em;\r\n}\r\n\r\nul li {\r\n    padding-left: 0.5" +
                    "em;\r\n}\r\n\r\nul.icons {\r\n    cursor: default;\r\n    list-style: none;\r\n    padding-l" +
                    "eft: 0;\r\n}\r\n\r\nul.icons li {\r\n    display: inline-block;\r\n    padding: 0 1em 0 0;" +
                    "\r\n}\r\n\r\nul.icons li:last-child {\r\n    padding-right: 0;\r\n}\r\n\r\nul.icons li .icon:b" +
                    "efore {\r\n    font-size: 1.25em;\r\n}\r\n\r\nul.icons li a {\r\n    color: inherit;\r\n}\r\n\r" +
                    "\n\r\n/* Form */\r\n\r\nform {\r\n    margin: 0 0 2em 0;\r\n}\r\n\r\nform .message {\r\n    text-" +
                    "decoration: none;\r\n    -moz-transition: opacity 0.2s ease-in-out, -moz-transform" +
                    " 0.2s ease-in-out;\r\n    -webkit-transition: opacity 0.2s ease-in-out, -webkit-tr" +
                    "ansform 0.2s ease-in-out;\r\n    -ms-transition: opacity 0.2s ease-in-out, -ms-tra" +
                    "nsform 0.2s ease-in-out;\r\n    transition: opacity 0.2s ease-in-out, transform 0." +
                    "2s ease-in-out;\r\n    -moz-transform: scale(1.05);\r\n    -webkit-transform: scale(" +
                    "1.05);\r\n    -ms-transform: scale(1.05);\r\n    transform: scale(1.05);\r\n    height" +
                    ": 2.75em;\r\n    line-height: 2.75em;\r\n    opacity: 0;\r\n}\r\n\r\nform .message:before " +
                    "{\r\n    -moz-osx-font-smoothing: grayscale;\r\n    -webkit-font-smoothing: antialia" +
                    "sed;\r\n    font-family: FontAwesome;\r\n    font-style: normal;\r\n    font-weight: n" +
                    "ormal;\r\n    text-transform: none !important;\r\n}\r\n\r\nform .message:before {\r\n    m" +
                    "argin-right: 0.5em;\r\n}\r\n\r\nform .message.visible {\r\n    -moz-transform: scale(1);" +
                    "\r\n    -webkit-transform: scale(1);\r\n    -ms-transform: scale(1);\r\n    transform:" +
                    " scale(1);\r\n    opacity: 1;\r\n}\r\n\r\nform .message.success {\r\n    color: #74B3CE;\r\n" +
                    "}\r\n\r\nform .message.success:before {\r\n    content: \'\\f00c\';\r\n}\r\n\r\nform .message.f" +
                    "ailure {\r\n    color: #ff2361;\r\n}\r\n\r\nform .message.failure:before {\r\n    content:" +
                    " \'\\f119\';\r\n}\r\n\r\nlabel {\r\n    color: #fff;\r\n    display: block;\r\n    font-size: 0" +
                    ".9em;\r\n    font-weight: 700;\r\n    margin: 0 0 1em 0;\r\n}\r\n\r\n@-moz-keyframes focus" +
                    " {\r\n    0% {\r\n        -moz-transform: scale(1);\r\n        -webkit-transform: scal" +
                    "e(1);\r\n        -ms-transform: scale(1);\r\n        transform: scale(1);\r\n    }\r\n  " +
                    "  50% {\r\n        -moz-transform: scale(1.025);\r\n        -webkit-transform: scale" +
                    "(1.025);\r\n        -ms-transform: scale(1.025);\r\n        transform: scale(1.025);" +
                    "\r\n    }\r\n    100% {\r\n        -moz-transform: scale(1);\r\n        -webkit-transfor" +
                    "m: scale(1);\r\n        -ms-transform: scale(1);\r\n        transform: scale(1);\r\n  " +
                    "  }\r\n}\r\n\r\n@-webkit-keyframes focus {\r\n    0% {\r\n        -moz-transform: scale(1)" +
                    ";\r\n        -webkit-transform: scale(1);\r\n        -ms-transform: scale(1);\r\n     " +
                    "   transform: scale(1);\r\n    }\r\n    50% {\r\n        -moz-transform: scale(1.025);" +
                    "\r\n        -webkit-transform: scale(1.025);\r\n        -ms-transform: scale(1.025);" +
                    "\r\n        transform: scale(1.025);\r\n    }\r\n    100% {\r\n        -moz-transform: s" +
                    "cale(1);\r\n        -webkit-transform: scale(1);\r\n        -ms-transform: scale(1);" +
                    "\r\n        transform: scale(1);\r\n    }\r\n}\r\n\r\n@-ms-keyframes focus {\r\n    0% {\r\n  " +
                    "      -moz-transform: scale(1);\r\n        -webkit-transform: scale(1);\r\n        -" +
                    "ms-transform: scale(1);\r\n        transform: scale(1);\r\n    }\r\n    50% {\r\n       " +
                    " -moz-transform: scale(1.025);\r\n        -webkit-transform: scale(1.025);\r\n      " +
                    "  -ms-transform: scale(1.025);\r\n        transform: scale(1.025);\r\n    }\r\n    100" +
                    "% {\r\n        -moz-transform: scale(1);\r\n        -webkit-transform: scale(1);\r\n  " +
                    "      -ms-transform: scale(1);\r\n        transform: scale(1);\r\n    }\r\n}\r\n\r\n@keyfr" +
                    "ames focus {\r\n    0% {\r\n        -moz-transform: scale(1);\r\n        -webkit-trans" +
                    "form: scale(1);\r\n        -ms-transform: scale(1);\r\n        transform: scale(1);\r" +
                    "\n    }\r\n    50% {\r\n        -moz-transform: scale(1.025);\r\n        -webkit-transf" +
                    "orm: scale(1.025);\r\n        -ms-transform: scale(1.025);\r\n        transform: sca" +
                    "le(1.025);\r\n    }\r\n    100% {\r\n        -moz-transform: scale(1);\r\n        -webki" +
                    "t-transform: scale(1);\r\n        -ms-transform: scale(1);\r\n        transform: sca" +
                    "le(1);\r\n    }\r\n}\r\n\r\ninput[type=\"text\"],\r\ninput[type=\"password\"],\r\ninput[type=\"em" +
                    "ail\"],\r\nselect,\r\ntextarea {\r\n    -moz-appearance: none;\r\n    -webkit-appearance:" +
                    " none;\r\n    -ms-appearance: none;\r\n    appearance: none;\r\n    -moz-transform: sc" +
                    "ale(1);\r\n    -webkit-transform: scale(1);\r\n    -ms-transform: scale(1);\r\n    tra" +
                    "nsform: scale(1);\r\n    -moz-transition: border-color 0.2s ease, background-color" +
                    " 0.2s ease;\r\n    -webkit-transition: border-color 0.2s ease, background-color 0." +
                    "2s ease;\r\n    -ms-transition: border-color 0.2s ease, background-color 0.2s ease" +
                    ";\r\n    transition: border-color 0.2s ease, background-color 0.2s ease;\r\n    back" +
                    "ground-color: transparent;\r\n    border-radius: 6px;\r\n    border: none;\r\n    bord" +
                    "er: solid 2px rgba(255, 255, 255, 0.35);\r\n    color: inherit;\r\n    display: bloc" +
                    "k;\r\n    outline: 0;\r\n    padding: 0 1em;\r\n    text-decoration: none;\r\n    width:" +
                    " 100%;\r\n}\r\n\r\ninput[type=\"text\"]:invalid,\r\ninput[type=\"password\"]:invalid,\r\ninput" +
                    "[type=\"email\"]:invalid,\r\nselect:invalid,\r\ntextarea:invalid {\r\n    box-shadow: no" +
                    "ne;\r\n}\r\n\r\ninput[type=\"text\"]:focus,\r\ninput[type=\"password\"]:focus,\r\ninput[type=\"" +
                    "email\"]:focus,\r\nselect:focus,\r\ntextarea:focus {\r\n    -moz-animation: focus 0.1s;" +
                    "\r\n    -webkit-animation: focus 0.1s;\r\n    -ms-animation: focus 0.1s;\r\n    animat" +
                    "ion: focus 0.1s;\r\n    background-color: rgba(255, 255, 255, 0.125);\r\n    border-" +
                    "color: #74B3CE;\r\n}\r\n\r\n.select-wrapper {\r\n    text-decoration: none;\r\n    display" +
                    ": block;\r\n    position: relative;\r\n}\r\n\r\n.select-wrapper:before {\r\n    -moz-osx-f" +
                    "ont-smoothing: grayscale;\r\n    -webkit-font-smoothing: antialiased;\r\n    font-fa" +
                    "mily: FontAwesome;\r\n    font-style: normal;\r\n    font-weight: normal;\r\n    text-" +
                    "transform: none !important;\r\n}\r\n\r\n.select-wrapper:before {\r\n    color: rgba(255," +
                    " 255, 255, 0.35);\r\n    content: \'\\f078\';\r\n    display: block;\r\n    height: 2.75e" +
                    "m;\r\n    line-height: 2.75em;\r\n    pointer-events: none;\r\n    position: absolute;" +
                    "\r\n    right: 0;\r\n    text-align: center;\r\n    top: 0;\r\n    width: 2.75em;\r\n}\r\n\r\n" +
                    ".select-wrapper select::-ms-expand {\r\n    display: none;\r\n}\r\n\r\ninput[type=\"text\"" +
                    "],\r\ninput[type=\"password\"],\r\ninput[type=\"email\"],\r\nselect {\r\n    height: 2.75em;" +
                    "\r\n}\r\n\r\ntextarea {\r\n    padding: 0.75em 1em;\r\n}\r\n\r\ninput[type=\"checkbox\"],\r\ninput" +
                    "[type=\"radio\"] {\r\n    -moz-appearance: none;\r\n    -webkit-appearance: none;\r\n   " +
                    " -ms-appearance: none;\r\n    appearance: none;\r\n    display: block;\r\n    float: l" +
                    "eft;\r\n    margin-right: -2em;\r\n    opacity: 0;\r\n    width: 1em;\r\n    z-index: -1" +
                    ";\r\n}\r\n\r\ninput[type=\"checkbox\"] + label,\r\ninput[type=\"radio\"] + label {\r\n    text" +
                    "-decoration: none;\r\n    color: rgba(255, 255, 255, 0.75);\r\n    cursor: pointer;\r" +
                    "\n    display: inline-block;\r\n    font-size: 1em;\r\n    font-weight: 400;\r\n    pad" +
                    "ding-left: 2.4em;\r\n    padding-right: 0.75em;\r\n    position: relative;\r\n}\r\n\r\ninp" +
                    "ut[type=\"checkbox\"] + label:before,\r\ninput[type=\"radio\"] + label:before {\r\n    -" +
                    "moz-osx-font-smoothing: grayscale;\r\n    -webkit-font-smoothing: antialiased;\r\n  " +
                    "  font-family: FontAwesome;\r\n    font-style: normal;\r\n    font-weight: normal;\r\n" +
                    "    text-transform: none !important;\r\n}\r\n\r\ninput[type=\"checkbox\"] + label:before" +
                    ",\r\ninput[type=\"radio\"] + label:before {\r\n    background: rgba(255, 255, 255, 0.1" +
                    "25);\r\n    border-radius: 6px;\r\n    border: solid 2px rgba(255, 255, 255, 0.35);\r" +
                    "\n    content: \'\';\r\n    display: inline-block;\r\n    height: 1.65em;\r\n    left: 0;" +
                    "\r\n    line-height: 1.58125em;\r\n    position: absolute;\r\n    text-align: center;\r" +
                    "\n    top: 0;\r\n    width: 1.65em;\r\n}\r\n\r\ninput[type=\"checkbox\"]:checked + label:be" +
                    "fore,\r\ninput[type=\"radio\"]:checked + label:before {\r\n    background: #74B3CE;\r\n " +
                    "   border-color: #74B3CE;\r\n    color: #ffffff;\r\n    content: \'\\f00c\';\r\n}\r\n\r\ninpu" +
                    "t[type=\"checkbox\"]:focus + label:before,\r\ninput[type=\"radio\"]:focus + label:befo" +
                    "re {\r\n    border-color: #74B3CE;\r\n    box-shadow: 0 0 0 2px #74B3CE;\r\n}\r\n\r\ninput" +
                    "[type=\"checkbox\"] + label:before {\r\n    border-radius: 6px;\r\n}\r\n\r\ninput[type=\"ra" +
                    "dio\"] + label:before {\r\n    border-radius: 100%;\r\n}\r\n\r\n::-webkit-input-placehold" +
                    "er {\r\n    color: rgba(255, 255, 255, 0.5) !important;\r\n    opacity: 1.0;\r\n}\r\n\r\n:" +
                    "-moz-placeholder {\r\n    color: rgba(255, 255, 255, 0.5) !important;\r\n    opacity" +
                    ": 1.0;\r\n}\r\n\r\n::-moz-placeholder {\r\n    color: rgba(255, 255, 255, 0.5) !importan" +
                    "t;\r\n    opacity: 1.0;\r\n}\r\n\r\n:-ms-input-placeholder {\r\n    color: rgba(255, 255, " +
                    "255, 0.5) !important;\r\n    opacity: 1.0;\r\n}\r\n\r\n.formerize-placeholder {\r\n    col" +
                    "or: rgba(255, 255, 255, 0.5) !important;\r\n    opacity: 1.0;\r\n}\r\n\r\n\r\n/* Button */" +
                    "\r\n\r\ninput[type=\"submit\"],\r\ninput[type=\"reset\"],\r\ninput[type=\"button\"],\r\nbutton,\r" +
                    "\n.button {\r\n    -moz-appearance: none;\r\n    -webkit-appearance: none;\r\n    -ms-a" +
                    "ppearance: none;\r\n    appearance: none;\r\n    -moz-transition: background-color 0" +
                    ".2s ease-in-out, color 0.2s ease-in-out, opacity 0.2s ease-in-out;\r\n    -webkit-" +
                    "transition: background-color 0.2s ease-in-out, color 0.2s ease-in-out, opacity 0" +
                    ".2s ease-in-out;\r\n    -ms-transition: background-color 0.2s ease-in-out, color 0" +
                    ".2s ease-in-out, opacity 0.2s ease-in-out;\r\n    transition: background-color 0.2" +
                    "s ease-in-out, color 0.2s ease-in-out, opacity 0.2s ease-in-out;\r\n    background" +
                    "-color: #74B3CE;\r\n    border-radius: 6px;\r\n    border: 0;\r\n    color: #ffffff !i" +
                    "mportant;\r\n    cursor: pointer;\r\n    display: inline-block;\r\n    font-weight: 70" +
                    "0;\r\n    height: 2.75em;\r\n    line-height: 2.75em;\r\n    padding: 0 1.125em;\r\n    " +
                    "text-align: center;\r\n    text-decoration: none;\r\n    white-space: nowrap;\r\n}\r\n\r\n" +
                    "input[type=\"submit\"]:hover,\r\ninput[type=\"reset\"]:hover,\r\ninput[type=\"button\"]:ho" +
                    "ver,\r\nbutton:hover,\r\n.button:hover {\r\n    background-color: white;\r\n}\r\n\r\ninput[t" +
                    "ype=\"submit\"]:active,\r\ninput[type=\"reset\"]:active,\r\ninput[type=\"button\"]:active," +
                    "\r\nbutton:active,\r\n.button:active {\r\n    background-color: #232621;\r\n}\r\n\r\ninput[t" +
                    "ype=\"submit\"].disabled,\r\ninput[type=\"submit\"]:disabled,\r\ninput[type=\"reset\"].dis" +
                    "abled,\r\ninput[type=\"reset\"]:disabled,\r\ninput[type=\"button\"].disabled,\r\ninput[typ" +
                    "e=\"button\"]:disabled,\r\nbutton.disabled,\r\nbutton:disabled,\r\n.button.disabled,\r\n.b" +
                    "utton:disabled {\r\n    opacity: 0.5;\r\n}\r\n\r\n@media screen and (max-width: 480px) {" +
                    "\r\n    input[type=\"submit\"],\r\n    input[type=\"reset\"],\r\n    input[type=\"button\"]," +
                    "\r\n    button,\r\n    .button {\r\n        padding: 0;\r\n    }\r\n}\r\n\r\n\r\n/* Header */\r\n\r" +
                    "\n#header h1 {\r\n    font-size: 3.25em;\r\n    margin: 0 0 0.55em 0;\r\n}\r\n\r\n#header p" +
                    " {\r\n    font-size: 1.35em;\r\n    line-height: 1.65em;\r\n}\r\n\r\n#header a {\r\n    colo" +
                    "r: inherit;\r\n}\r\n\r\n@media screen and (max-width: 736px) {\r\n    #header h1 {\r\n    " +
                    "    font-size: 2em;\r\n    }\r\n    #header p {\r\n        font-size: 1em;\r\n    }\r\n}\r\n" +
                    "\r\n@media screen and (max-width: 480px) {\r\n    #header {\r\n        margin: 0 0 1em" +
                    " 0;\r\n    }\r\n}\r\n\r\n\r\n/* Signup Form */\r\n\r\n#signup-form {\r\n    display: -moz-flex;\r" +
                    "\n    display: -webkit-flex;\r\n    display: -ms-flex;\r\n    display: flex;\r\n    pos" +
                    "ition: relative;\r\n}\r\n\r\n#signup-form input[type=\"text\"],\r\n#signup-form input[type" +
                    "=\"password\"],\r\n#signup-form input[type=\"email\"] {\r\n    width: 18em;\r\n}\r\n\r\n#signu" +
                    "p-form > * {\r\n    margin: 0 0 0 1em;\r\n}\r\n\r\n#signup-form >:first-child {\r\n    mar" +
                    "gin: 0 0 0 0;\r\n}\r\n\r\n@media screen and (max-width: 480px) {\r\n    #signup-form {\r\n" +
                    "        -moz-flex-direction: column;\r\n        -webkit-flex-direction: column;\r\n " +
                    "       -ms-flex-direction: column;\r\n        flex-direction: column;\r\n    }\r\n    " +
                    "#signup-form input[type=\"type\"],\r\n    #signup-form input[type=\"password\"],\r\n    " +
                    "#signup-form input[type=\"email\"] {\r\n        width: 100%;\r\n    }\r\n    #signup-for" +
                    "m > * {\r\n        margin: 1.25em 0 0 0;\r\n    }\r\n    #signup-form .message {\r\n    " +
                    "    bottom: -1.5em;\r\n        font-size: 0.9em;\r\n        height: 1em;\r\n        le" +
                    "ft: 0;\r\n        line-height: inherit;\r\n        margin-top: 0;\r\n        position:" +
                    " absolute;\r\n    }\r\n}\r\n\r\n\r\n/* Footer */\r\n\r\n#footer {\r\n    -moz-transition: opacit" +
                    "y 0.5s ease-in-out;\r\n    -webkit-transition: opacity 0.5s ease-in-out;\r\n    -ms-" +
                    "transition: opacity 0.5s ease-in-out;\r\n    transition: opacity 0.5s ease-in-out;" +
                    "\r\n    bottom: 4em;\r\n    color: rgba(255, 255, 255, 0.5);\r\n    left: 4em;\r\n    op" +
                    "acity: 0.5;\r\n    position: absolute;\r\n}\r\n\r\n#footer .icons {\r\n    margin: 0 0 0.5" +
                    "em 0;\r\n}\r\n\r\n#footer .copyright {\r\n    font-size: 0.8em;\r\n    list-style: none;\r\n" +
                    "    padding: 0;\r\n}\r\n\r\n#footer .copyright li {\r\n    border-left: solid 1px rgba(2" +
                    "55, 255, 255, 0.25);\r\n    display: inline-block;\r\n    line-height: 1em;\r\n    mar" +
                    "gin: 0 0 0 0.75em;\r\n    padding: 0 0 0 0.75em;\r\n}\r\n\r\n#footer .copyright li:first" +
                    "-child {\r\n    border-left: 0;\r\n    margin-left: 0;\r\n    padding-left: 0;\r\n}\r\n\r\n#" +
                    "footer .copyright a {\r\n    color: inherit;\r\n}\r\n\r\n#footer:hover {\r\n    opacity: 1" +
                    ";\r\n}\r\n\r\n#footer >:last-child {\r\n    margin-bottom: 0;\r\n}\r\n\r\np.small {\r\n    displ" +
                    "ay: inline-block;\r\n    font-size: 75%;\r\n    color: slategray;\r\n}\r\n\r\n@media scree" +
                    "n and (max-width: 1680px) {\r\n    #footer {\r\n        bottom: 3.5em;\r\n        left" +
                    ": 3.5em;\r\n    }\r\n    p.small {\r\n        padding-left: 400px;\r\n    }\r\n}\r\n\r\n@media" +
                    " screen and (max-width: 736px) {\r\n    #footer {\r\n        bottom: 2em;\r\n        l" +
                    "eft: 2em;\r\n    }\r\n    p.small {\r\n        padding-left: 0px;\r\n    }\r\n}\r\n\r\n@media " +
                    "screen and (max-width: 360px) {\r\n    #footer {\r\n        bottom: 1.25em;\r\n       " +
                    " left: 1.25em;\r\n    }\r\n}\r\n\r\n@media screen and (max-height: 640px) {\r\n    #footer" +
                    " {\r\n        bottom: auto;\r\n        left: auto;\r\n        margin: 1em 0 0 0;\r\n    " +
                    "    position: relative;\r\n    }\r\n}\r\n\t\t</style>\r\n</head>\r\n<body>\r\n\r\n\t<!-- Header -" +
                    "->\r\n\t<header id=\"header\">\r\n\t\t<h1>");
            
            #line 1315 "C:\Users\alist\Source\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Manifest.ApplicationName));
            
            #line default
            #line hidden
            this.Write("</h1>\r\n\t\t<h2>");
            
            #line 1316 "C:\Users\alist\Source\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Manifest.AuthorName));
            
            #line default
            #line hidden
            this.Write("</h2>\r\n\t\t<h3>");
            
            #line 1317 "C:\Users\alist\Source\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Manifest.PublisherName));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n\t\t<p>\r\n\t\t\t");
            
            #line 1319 "C:\Users\alist\Source\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Manifest.SuiteName));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t</p>\r\n\t\t<p>\r\n\t\t\t");
            
            #line 1322 "C:\Users\alist\Source\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Manifest.Summary));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t</p>\r\n\t</header>\r\n\t<p>");
            
            #line 1325 "C:\Users\alist\Source\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Manifest.Description));
            
            #line default
            #line hidden
            this.Write("</p>\r\n\t<!-- Signup Form -->\r\n\t<form id=\"signup-form\" method=\"post\" action=\"#\">\r\n\t" +
                    "\t<input type=\"text\" disabled placeholder=\"Requires .NET Framework ");
            
            #line 1328 "C:\Users\alist\Source\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Manifest.FrameworkVersion));
            
            #line default
            #line hidden
            this.Write("\" ></input>\r\n\t\t<a class=\"button btn-lg\" href=\"");
            
            #line 1329 "C:\Users\alist\Source\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AppLauncher.Name));
            
            #line default
            #line hidden
            this.Write("\">Launch</a>\r\n\t\t");
            
            #line 1330 "C:\Users\alist\Source\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"

		if (!string.IsNullOrWhiteSpace(AdditionalLink.Key))
		{
		
            
            #line default
            #line hidden
            this.Write("\t\t<a class=\"button btn-lg\" href=\"");
            
            #line 1334 "C:\Users\alist\Source\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AdditionalLink.Value));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 1334 "C:\Users\alist\Source\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AdditionalLink.Key));
            
            #line default
            #line hidden
            this.Write("</a>\r\n\t\t");
            
            #line 1335 "C:\Users\alist\Source\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"

		}
		
            
            #line default
            #line hidden
            this.Write("\t\t<a class=\"button btn-lg install\" href=\"setup.exe\">Install</a>\r\n\t</form>\r\n\t<!-- " +
                    "Footer -->\r\n\t<footer id=\"footer\">\r\n\t\t<ul class=\"copyright\">\r\n\t\t\t\r\n\t\t\t");
            
            #line 1344 "C:\Users\alist\Source\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
 
				if(!string.IsNullOrWhiteSpace(Model.Manifest.Copyright))
				{
				
            
            #line default
            #line hidden
            this.Write("\t\t\t\t<li>\r\n\t\t\t\t© ");
            
            #line 1349 "C:\Users\alist\Source\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Manifest.Copyright));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t</li>\r\n\t\t\t\t");
            
            #line 1351 "C:\Users\alist\Source\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"

				}
				
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\r\n\t\t\t<li><a href=\"http://html5up.net\">HTML5 UP</a></li>\r\n\t\t\t<li><a href=\"htt" +
                    "ps://bitbucket.org/agc93/clicktwice\" target=\"_blank\">ClickTwice</a></li>\r\n\t\t</ul" +
                    ">\r\n\t</footer>\r\n\r\n\t<!-- Scripts -->\r\n\t<!--[if lte IE 8]><script src=\"assets/js/ie" +
                    "/respond.min.js\"></script><![endif]-->\r\n<!-- <script src=\"assets/js/main.js\"></s" +
                    "cript> -->\r\n<script type=\"text/javascript\">\r\n/*\r\n\tEventually by HTML5 UP\r\n\thtml5" +
                    "up.net | @n33co\r\n\tFree for personal and commercial use under the CCA 3.0 license" +
                    " (html5up.net/license)\r\n*/\r\n\r\n(function() {\r\n\r\n\t\"use strict\";\r\n\r\n\t// Methods/pol" +
                    "yfills.\r\n\r\n\t\t// classList | (c) @remy | github.com/remy/polyfills | rem.mit-lice" +
                    "nse.org\r\n\t\t\t!function(){function t(t){this.el=t;for(var n=t.className.replace(/^" +
                    "\\s+|\\s+$/g,\"\").split(/\\s+/),i=0;i<n.length;i++)e.call(this,n[i])}function n(t,n," +
                    "i){Object.defineProperty?Object.defineProperty(t,n,{get:i}):t.__defineGetter__(n" +
                    ",i)}if(!(\"undefined\"==typeof window.Element||\"classList\"in document.documentElem" +
                    "ent)){var i=Array.prototype,e=i.push,s=i.splice,o=i.join;t.prototype={add:functi" +
                    "on(t){this.contains(t)||(e.call(this,t),this.el.className=this.toString())},cont" +
                    "ains:function(t){return-1!=this.el.className.indexOf(t)},item:function(t){return" +
                    " this[t]||null},remove:function(t){if(this.contains(t)){for(var n=0;n<this.lengt" +
                    "h&&this[n]!=t;n++);s.call(this,n,1),this.el.className=this.toString()}},toString" +
                    ":function(){return o.call(this,\" \")},toggle:function(t){return this.contains(t)?" +
                    "this.remove(t):this.add(t),this.contains(t)}},window.DOMTokenList=t,n(Element.pr" +
                    "ototype,\"classList\",function(){return new t(this)})}}();\r\n\r\n\t\t// canUse\r\n\t\t\twind" +
                    "ow.canUse=function(p){if(!window._canUse)window._canUse=document.createElement(\"" +
                    "div\");var e=window._canUse.style,up=p.charAt(0).toUpperCase()+p.slice(1);return " +
                    "p in e||\"Moz\"+up in e||\"Webkit\"+up in e||\"O\"+up in e||\"ms\"+up in e};\r\n\r\n\t\t// win" +
                    "dow.addEventListener\r\n\t\t\t(function(){if(\"addEventListener\"in window)return;windo" +
                    "w.addEventListener=function(type,f){window.attachEvent(\"on\"+type,f)}})();\r\n\r\n\t//" +
                    " Vars.\r\n\t\tvar\t$body = document.querySelector(\'body\');\r\n\r\n\t// Disable animations/" +
                    "transitions until everything\'s loaded.\r\n\t\t$body.classList.add(\'is-loading\');\r\n\r\n" +
                    "\t\twindow.addEventListener(\'load\', function() {\r\n\t\t\twindow.setTimeout(function() " +
                    "{\r\n\t\t\t\t$body.classList.remove(\'is-loading\');\r\n\t\t\t}, 100);\r\n\t\t});\r\n\r\n\t// Slidesho" +
                    "w Background.\r\n\t\t(function() {\r\n\t\t\t// Settings.\r\n\t\t\t\tvar settings = {\r\n\r\n\t\t\t\t\t//" +
                    " Images (in the format of \'url\': \'alignment\').\r\n\t\t\t\t\t\timages: {\r\n\t\t\t\t\t\t");
            
            #line 1405 "C:\Users\alist\Source\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"

						foreach (var img in Images)
						{
							if (img == Images.Last())
							{
							
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\'");
            
            #line 1411 "C:\Users\alist\Source\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(img));
            
            #line default
            #line hidden
            this.Write("\' : \'center\'\r\n\t\t\t\t\t\t");
            
            #line 1412 "C:\Users\alist\Source\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"

						}
						else 
						{
						
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\'");
            
            #line 1417 "C:\Users\alist\Source\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(img));
            
            #line default
            #line hidden
            this.Write("\' : \'center\',\r\n\t\t\t\t\t\t");
            
            #line 1418 "C:\Users\alist\Source\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"

						}
					}
					
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t},\r\n\r\n\t\t\t\t\t// Delay.\r\n\t\t\t\t\t\tdelay: 6000\r\n\r\n\t\t\t\t};\r\n\r\n\t\t\t// Vars.\r\n\t\t\t\tvar\tp" +
                    "os = 0, lastPos = 0,\r\n\t\t\t\t\t$wrapper, $bgs = [], $bg,\r\n\t\t\t\t\tk, v;\r\n\r\n\t\t\t// Create" +
                    " BG wrapper, BGs.\r\n\t\t\t\t$wrapper = document.createElement(\'div\');\r\n\t\t\t\t\t$wrapper." +
                    "id = \'bg\';\r\n\t\t\t\t\t$body.appendChild($wrapper);\r\n\r\n\t\t\t\tfor (k in settings.images) " +
                    "{\r\n\r\n\t\t\t\t\t// Create BG.\r\n\t\t\t\t\t\t$bg = document.createElement(\'div\');\r\n\t\t\t\t\t\t\t$bg." +
                    "style.backgroundImage = \'url(\"\' + k + \'\")\';\r\n\t\t\t\t\t\t\t$bg.style.backgroundPosition" +
                    " = settings.images[k];\r\n\t\t\t\t\t\t\t$wrapper.appendChild($bg);\r\n\r\n\t\t\t\t\t// Add it to a" +
                    "rray.\r\n\t\t\t\t\t\t$bgs.push($bg);\r\n\r\n\t\t\t\t}\r\n\r\n\t\t\t// Main loop.\r\n\t\t\t\t$bgs[pos].classLi" +
                    "st.add(\'visible\');\r\n\t\t\t\t$bgs[pos].classList.add(\'top\');\r\n\r\n\t\t\t\t// Bail if we onl" +
                    "y have a single BG or the client doesn\'t support transitions.\r\n\t\t\t\t\tif ($bgs.len" +
                    "gth == 1\r\n\t\t\t\t\t||\t!canUse(\'transition\'))\r\n\t\t\t\t\t\treturn;\r\n\r\n\t\t\t\twindow.setInterva" +
                    "l(function() {\r\n\r\n\t\t\t\t\tlastPos = pos;\r\n\t\t\t\t\tpos++;\r\n\r\n\t\t\t\t\t// Wrap to beginning " +
                    "if necessary.\r\n\t\t\t\t\t\tif (pos >= $bgs.length)\r\n\t\t\t\t\t\t\tpos = 0;\r\n\r\n\t\t\t\t\t// Swap to" +
                    "p images.\r\n\t\t\t\t\t\t$bgs[lastPos].classList.remove(\'top\');\r\n\t\t\t\t\t\t$bgs[pos].classLi" +
                    "st.add(\'visible\');\r\n\t\t\t\t\t\t$bgs[pos].classList.add(\'top\');\r\n\r\n\t\t\t\t\t// Hide last i" +
                    "mage after a short delay.\r\n\t\t\t\t\t\twindow.setTimeout(function() {\r\n\t\t\t\t\t\t\t$bgs[las" +
                    "tPos].classList.remove(\'visible\');\r\n\t\t\t\t\t\t}, settings.delay / 2);\r\n\r\n\t\t\t\t}, sett" +
                    "ings.delay);\r\n\r\n\t\t})();\r\n\r\n\t// Signup Form.\r\n\t\t(function() {\r\n\r\n\t\t\t// Vars.\r\n\t\t\t" +
                    "\tvar $form = document.querySelectorAll(\'#signup-form\')[0],\r\n\t\t\t\t\t$submit = docum" +
                    "ent.querySelectorAll(\'#signup-form input[type=\"submit\"]\')[0],\r\n\t\t\t\t\t$message;\r\n\r" +
                    "\n\t\t\t// Bail if addEventListener isn\'t supported.\r\n\t\t\t\tif (!(\'addEventListener\' i" +
                    "n $form))\r\n\t\t\t\t\treturn;\r\n\r\n\t\t\t// Message.\r\n\t\t\t\t$message = document.createElement" +
                    "(\'span\');\r\n\t\t\t\t\t$message.classList.add(\'message\');\r\n\t\t\t\t\t$form.appendChild($mess" +
                    "age);\r\n\r\n\t\t\t\t$message._show = function(type, text) {\r\n\r\n\t\t\t\t\t$message.innerHTML " +
                    "= text;\r\n\t\t\t\t\t$message.classList.add(type);\r\n\t\t\t\t\t$message.classList.add(\'visibl" +
                    "e\');\r\n\r\n\t\t\t\t\twindow.setTimeout(function() {\r\n\t\t\t\t\t\t$message._hide();\r\n\t\t\t\t\t}, 30" +
                    "00);\r\n\r\n\t\t\t\t};\r\n\r\n\t\t\t\t$message._hide = function() {\r\n\t\t\t\t\t$message.classList.rem" +
                    "ove(\'visible\');\r\n\t\t\t\t};\r\n\r\n\t\t\t// Events.\r\n\t\t\t// Note: If you\'re *not* using AJAX" +
                    ", get rid of this event listener.\r\n\t\t\t\t$form.addEventListener(\'submit\', function" +
                    "(event) {\r\n\r\n\t\t\t\t\tevent.stopPropagation();\r\n\t\t\t\t\tevent.preventDefault();\r\n\r\n\t\t\t\t" +
                    "\t// Hide message.\r\n\t\t\t\t\t\t$message._hide();\r\n\r\n\t\t\t\t\t// Disable submit.\r\n\t\t\t\t\t\t$su" +
                    "bmit.disabled = true;\r\n\r\n\t\t\t\t\t// Process form.\r\n\t\t\t\t\t// Note: Doesn\'t actually d" +
                    "o anything yet (other than report back with a \"thank you\"),\r\n\t\t\t\t\t// but there\'s" +
                    " enough here to piece together a working AJAX submission call that does.\r\n\t\t\t\t\t\t" +
                    "window.setTimeout(function() {\r\n\r\n\t\t\t\t\t\t\t// Reset form.\r\n\t\t\t\t\t\t\t\t$form.reset();\r" +
                    "\n\r\n\t\t\t\t\t\t\t// Enable submit.\r\n\t\t\t\t\t\t\t\t$submit.disabled = false;\r\n\r\n\t\t\t\t\t\t\t// Show" +
                    " message.\r\n\t\t\t\t\t\t\t\t$message._show(\'success\', \'Thank you!\');\r\n\t\t\t\t\t\t\t\t//$message." +
                    "_show(\'failure\', \'Something went wrong. Please try again.\');\r\n\r\n\t\t\t\t\t\t}, 750);\r\n" +
                    "\r\n\t\t\t\t});\r\n\r\n\t\t})();\r\n\r\n})();\r\n</script>\r\n\r\n</body>\r\n</html>\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class LaunchPageBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
