// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ClickTwice.Publisher.Core.Resources
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\ucrm4\Source\Repos\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class LaunchPage : LaunchPageBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n<!DOCTYPE HTML>\r\n<!--\r\n    Eventually by HTML5 UP\r\n    \r\n    Free for personal " +
                    "and commercial use under the CCA 3.0 license (html5up.net/license)\r\n-->\r\n<html>\r" +
                    "\n<head>\r\n    <title>");
            
            #line 16 "C:\Users\ucrm4\Source\Repos\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Manifest.ApplicationName));
            
            #line default
            #line hidden
            this.Write("</title>\r\n    <meta charset=\"utf-8\" />\r\n    <meta name=\"viewport\" content=\"width=" +
                    "device-width, initial-scale=1, user-scalable=no\" />\r\n    <!-- <link rel=\"stylesh" +
                    "eet\" href=\"assets/css/main.css\"/> -->\r\n\t<link rel=\"stylesheet\" href=\"https://max" +
                    "cdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\" />\r\n    <style" +
                    ">\r\n\t@import url(\"http://fonts.googleapis.com/css?family=Roboto:400,700\");\r\n\r\n/*\r" +
                    "\n\tEventually by HTML5 UP\r\n\thtml5up.net | @n33co\r\n\tFree for personal and commerci" +
                    "al use under the CCA 3.0 license (html5up.net/license)\r\n*/\r\n\r\n/* Reset */\r\n\r\n\tht" +
                    "ml, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquo" +
                    "te, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd" +
                    ", q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt," +
                    " dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, th" +
                    "ead, tr, th, td, article, aside, canvas, details, embed, figure, figcaption, foo" +
                    "ter, header, hgroup, menu, nav, output, ruby, section, summary, time, mark, audi" +
                    "o, video {\r\n\t\tmargin: 0;\r\n\t\tpadding: 0;\r\n\t\tborder: 0;\r\n\t\tfont-size: 100%;\r\n\t\tfon" +
                    "t: inherit;\r\n\t\tvertical-align: baseline;\r\n\t}\r\n\r\n\tarticle, aside, details, figcap" +
                    "tion, figure, footer, header, hgroup, menu, nav, section {\r\n\t\tdisplay: block;\r\n\t" +
                    "}\r\n\r\n\tbody {\r\n\t\tline-height: 1;\r\n\t}\r\n\r\n\tol, ul {\r\n\t\tlist-style: none;\r\n\t}\r\n\r\n\tbl" +
                    "ockquote, q {\r\n\t\tquotes: none;\r\n\t}\r\n\r\n\tblockquote:before, blockquote:after, q:be" +
                    "fore, q:after {\r\n\t\tcontent: \'\';\r\n\t\tcontent: none;\r\n\t}\r\n\r\n\ttable {\r\n\t\tborder-coll" +
                    "apse: collapse;\r\n\t\tborder-spacing: 0;\r\n\t}\r\n\r\n\tbody {\r\n\t\t-webkit-text-size-adjust" +
                    ": none;\r\n\t}\r\n\r\n/* Box Model */\r\n\r\n\t*, *:before, *:after {\r\n\t\t-moz-box-sizing: bo" +
                    "rder-box;\r\n\t\t-webkit-box-sizing: border-box;\r\n\t\tbox-sizing: border-box;\r\n\t}\r\n\r\n/" +
                    "* Basic */\r\n\r\n\t@-ms-viewport {\r\n\t\twidth: device-width;\r\n\t}\r\n\r\n\tbody {\r\n\t\t-ms-ove" +
                    "rflow-style: scrollbar;\r\n\t}\r\n\r\n\t@media screen and (max-width: 480px) {\r\n\r\n\t\thtml" +
                    ", body {\r\n\t\t\tmin-width: 320px;\r\n\t\t}\r\n\r\n\t}\r\n\r\n\thtml, body {\r\n\t\theight: 100%;\r\n\t\to" +
                    "verflow-x: hidden;\r\n\t\twidth: 100%;\r\n\t}\r\n\r\n\t\t@media screen and (max-height: 640px" +
                    ") {\r\n\r\n\t\t\thtml, body {\r\n\t\t\t\theight: auto;\r\n\t\t\t\tmin-height: 100%;\r\n\t\t\t}\r\n\r\n\t\t}\r\n\r" +
                    "\n\tbody {\r\n\t\tdisplay: -moz-flex;\r\n\t\tdisplay: -webkit-flex;\r\n\t\tdisplay: -ms-flex;\r" +
                    "\n\t\tdisplay: flex;\r\n\t\t-moz-flex-direction: column;\r\n\t\t-webkit-flex-direction: col" +
                    "umn;\r\n\t\t-ms-flex-direction: column;\r\n\t\tflex-direction: column;\r\n\t\t-moz-justify-c" +
                    "ontent: center;\r\n\t\t-webkit-justify-content: center;\r\n\t\t-ms-justify-content: cent" +
                    "er;\r\n\t\tjustify-content: center;\r\n\t\tbackground-color: #000;\r\n\t\tpadding: 6em 4em 4" +
                    "em 4em;\r\n\t}\r\n\r\n\t\tbody > * {\r\n\t\t\tposition: relative;\r\n\t\t\tz-index: 2;\r\n\t\t}\r\n\r\n\t\tbo" +
                    "dy.is-loading *, body.is-loading *:before, body.is-loading *:after {\r\n\t\t\t-moz-an" +
                    "imation: none !important;\r\n\t\t\t-webkit-animation: none !important;\r\n\t\t\t-ms-animat" +
                    "ion: none !important;\r\n\t\t\tanimation: none !important;\r\n\t\t\t-moz-transition: none " +
                    "!important;\r\n\t\t\t-webkit-transition: none !important;\r\n\t\t\t-ms-transition: none !i" +
                    "mportant;\r\n\t\t\ttransition: none !important;\r\n\t\t}\r\n\r\n\t\t@media screen and (max-widt" +
                    "h: 1680px) {\r\n\r\n\t\t\tbody {\r\n\t\t\t\tpadding: 6em 3.5em 3.5em 3.5em;\r\n\t\t\t}\r\n\r\n\t\t}\r\n\r\n\t" +
                    "\t@media screen and (max-width: 736px) {\r\n\r\n\t\t\tbody {\r\n\t\t\t\tpadding: 5em 2em 2em 2" +
                    "em;\r\n\t\t\t}\r\n\r\n\t\t}\r\n\r\n\t\t@media screen and (max-width: 360px) {\r\n\r\n\t\t\tbody {\r\n\t\t\t\tp" +
                    "adding: 5em 1.25em 1.25em 1.25em;\r\n\t\t\t}\r\n\r\n\t\t}\r\n\r\n/* BG */\r\n\r\n\t#bg {\r\n\t\t-moz-tra" +
                    "nsition: opacity 2s ease-in-out;\r\n\t\t-webkit-transition: opacity 2s ease-in-out;\r" +
                    "\n\t\t-ms-transition: opacity 2s ease-in-out;\r\n\t\ttransition: opacity 2s ease-in-out" +
                    ";\r\n\t\theight: 100%;\r\n\t\tleft: 0;\r\n\t\topacity: 0.25;\r\n\t\tposition: fixed;\r\n\t\ttop: 0;\r" +
                    "\n\t\twidth: 100%;\r\n\t\tz-index: 1;\r\n\t}\r\n\r\n\t\t#bg div {\r\n\t\t\t-moz-transition: opacity 3" +
                    "s ease, visibility 3s;\r\n\t\t\t-webkit-transition: opacity 3s ease, visibility 3s;\r\n" +
                    "\t\t\t-ms-transition: opacity 3s ease, visibility 3s;\r\n\t\t\ttransition: opacity 3s ea" +
                    "se, visibility 3s;\r\n\t\t\tbackground-size: cover;\r\n\t\t\theight: 100%;\r\n\t\t\tleft: 0;\r\n\t" +
                    "\t\topacity: 0;\r\n\t\t\tposition: absolute;\r\n\t\t\ttop: 0;\r\n\t\t\tvisibility: hidden;\r\n\t\t\twi" +
                    "dth: 150%;\r\n\t\t}\r\n\r\n\t\t\t#bg div.visible {\r\n\t\t\t\t-moz-animation: bg 45s linear infin" +
                    "ite;\r\n\t\t\t\t-webkit-animation: bg 45s linear infinite;\r\n\t\t\t\t-ms-animation: bg 45s " +
                    "linear infinite;\r\n\t\t\t\tanimation: bg 45s linear infinite;\r\n\t\t\t\topacity: 1;\r\n\t\t\t\tv" +
                    "isibility: visible;\r\n\t\t\t\tz-index: 1;\r\n\t\t\t}\r\n\r\n\t\t\t\t#bg div.visible.top {\r\n\t\t\t\t\tz-" +
                    "index: 2;\r\n\t\t\t\t}\r\n\r\n\t\t\t\t@media screen and (max-width: 1280px) {\r\n\r\n\t\t\t\t\t#bg div." +
                    "visible {\r\n\t\t\t\t\t\t-moz-animation: bg 29.25s linear infinite;\r\n\t\t\t\t\t\t-webkit-anima" +
                    "tion: bg 29.25s linear infinite;\r\n\t\t\t\t\t\t-ms-animation: bg 29.25s linear infinite" +
                    ";\r\n\t\t\t\t\t\tanimation: bg 29.25s linear infinite;\r\n\t\t\t\t\t}\r\n\r\n\t\t\t\t}\r\n\r\n\t\t\t\t@media sc" +
                    "reen and (max-width: 736px) {\r\n\r\n\t\t\t\t\t#bg div.visible {\r\n\t\t\t\t\t\t-moz-animation: b" +
                    "g 18s linear infinite;\r\n\t\t\t\t\t\t-webkit-animation: bg 18s linear infinite;\r\n\t\t\t\t\t\t" +
                    "-ms-animation: bg 18s linear infinite;\r\n\t\t\t\t\t\tanimation: bg 18s linear infinite;" +
                    "\r\n\t\t\t\t\t}\r\n\r\n\t\t\t\t}\r\n\r\n\t\t\t#bg div:only-child {\r\n\t\t\t\t-moz-animation-direction: alte" +
                    "rnate !important;\r\n\t\t\t\t-webkit-animation-direction: alternate !important;\r\n\t\t\t\t-" +
                    "ms-animation-direction: alternate !important;\r\n\t\t\t\tanimation-direction: alternat" +
                    "e !important;\r\n\t\t\t}\r\n\r\n\t\tbody.is-loading #bg {\r\n\t\t\topacity: 0;\r\n\t\t}\r\n\r\n\t@-moz-ke" +
                    "yframes bg {\r\n\t\t0% {\r\n\t\t\t-moz-transform: translateX(0);\r\n\t\t\t-webkit-transform: t" +
                    "ranslateX(0);\r\n\t\t\t-ms-transform: translateX(0);\r\n\t\t\ttransform: translateX(0);\r\n\t" +
                    "\t}\r\n\r\n\t\t100% {\r\n\t\t\t-moz-transform: translateX(-25%);\r\n\t\t\t-webkit-transform: tran" +
                    "slateX(-25%);\r\n\t\t\t-ms-transform: translateX(-25%);\r\n\t\t\ttransform: translateX(-25" +
                    "%);\r\n\t\t}\r\n\t}\r\n\r\n\t@-webkit-keyframes bg {\r\n\t\t0% {\r\n\t\t\t-moz-transform: translateX(" +
                    "0);\r\n\t\t\t-webkit-transform: translateX(0);\r\n\t\t\t-ms-transform: translateX(0);\r\n\t\t\t" +
                    "transform: translateX(0);\r\n\t\t}\r\n\r\n\t\t100% {\r\n\t\t\t-moz-transform: translateX(-25%);" +
                    "\r\n\t\t\t-webkit-transform: translateX(-25%);\r\n\t\t\t-ms-transform: translateX(-25%);\r\n" +
                    "\t\t\ttransform: translateX(-25%);\r\n\t\t}\r\n\t}\r\n\r\n\t@-ms-keyframes bg {\r\n\t\t0% {\r\n\t\t\t-mo" +
                    "z-transform: translateX(0);\r\n\t\t\t-webkit-transform: translateX(0);\r\n\t\t\t-ms-transf" +
                    "orm: translateX(0);\r\n\t\t\ttransform: translateX(0);\r\n\t\t}\r\n\r\n\t\t100% {\r\n\t\t\t-moz-tran" +
                    "sform: translateX(-25%);\r\n\t\t\t-webkit-transform: translateX(-25%);\r\n\t\t\t-ms-transf" +
                    "orm: translateX(-25%);\r\n\t\t\ttransform: translateX(-25%);\r\n\t\t}\r\n\t}\r\n\r\n\t@keyframes " +
                    "bg {\r\n\t\t0% {\r\n\t\t\t-moz-transform: translateX(0);\r\n\t\t\t-webkit-transform: translate" +
                    "X(0);\r\n\t\t\t-ms-transform: translateX(0);\r\n\t\t\ttransform: translateX(0);\r\n\t\t}\r\n\r\n\t\t" +
                    "100% {\r\n\t\t\t-moz-transform: translateX(-25%);\r\n\t\t\t-webkit-transform: translateX(-" +
                    "25%);\r\n\t\t\t-ms-transform: translateX(-25%);\r\n\t\t\ttransform: translateX(-25%);\r\n\t\t}" +
                    "\r\n\t}\r\n\r\n/* Type */\r\n\r\n\tbody, input, select, textarea {\r\n\t\tcolor: rgba(255, 255, " +
                    "255, 0.75);\r\n\t\tfont-family: \"Roboto\", sans-serif;\r\n\t\tfont-size: 16pt;\r\n\t\tfont-we" +
                    "ight: 400;\r\n\t\tletter-spacing: -0.01em;\r\n\t\tline-height: 1.65em;\r\n\t}\r\n\r\n\t\t@media s" +
                    "creen and (max-width: 1680px) {\r\n\r\n\t\t\tbody, input, select, textarea {\r\n\t\t\t\tfont-" +
                    "size: 12pt;\r\n\t\t\t}\r\n\r\n\t\t}\r\n\r\n\t\t@media screen and (max-width: 1280px) {\r\n\r\n\t\t\tbody" +
                    ", input, select, textarea {\r\n\t\t\t\tfont-size: 11pt;\r\n\t\t\t}\r\n\r\n\t\t}\r\n\r\n\t\t@media scree" +
                    "n and (max-width: 980px) {\r\n\r\n\t\t\tbody, input, select, textarea {\r\n\t\t\t\tfont-size:" +
                    " 12pt;\r\n\t\t\t}\r\n\r\n\t\t}\r\n\r\n\t\t@media screen and (max-width: 736px) {\r\n\r\n\t\t\tbody, inpu" +
                    "t, select, textarea {\r\n\t\t\t\tfont-size: 12pt;\r\n\t\t\t}\r\n\r\n\t\t}\r\n\r\n\t\t@media screen and " +
                    "(max-width: 480px) {\r\n\r\n\t\t\tbody, input, select, textarea {\r\n\t\t\t\tfont-size: 12pt;" +
                    "\r\n\t\t\t}\r\n\r\n\t\t}\r\n\r\n\ta {\r\n\t\t-moz-transition: border-bottom-color 0.2s ease, color 0" +
                    ".2s ease;\r\n\t\t-webkit-transition: border-bottom-color 0.2s ease, color 0.2s ease;" +
                    "\r\n\t\t-ms-transition: border-bottom-color 0.2s ease, color 0.2s ease;\r\n\t\ttransitio" +
                    "n: border-bottom-color 0.2s ease, color 0.2s ease;\r\n\t\tborder-bottom: dotted 1px " +
                    "rgba(255, 255, 255, 0.25);\r\n\t\tcolor: #1cb495;\r\n\t\ttext-decoration: none;\r\n\t}\r\n\r\n\t" +
                    "\ta:hover {\r\n\t\t\tborder-bottom-color: transparent;\r\n\t\t\tcolor: #1cb495 !important;\r" +
                    "\n\t\t\ttext-decoration: none;\r\n\t\t}\r\n\r\n\tstrong, b {\r\n\t\tcolor: #fff;\r\n\t\tfont-weight: " +
                    "700;\r\n\t}\r\n\r\n\tem, i {\r\n\t\tfont-style: italic;\r\n\t}\r\n\r\n\tp {\r\n\t\tmargin: 0 0 2em 0;\r\n\t" +
                    "}\r\n\r\n\th1, h2, h3, h4, h5, h6 {\r\n\t\tcolor: #fff;\r\n\t\tfont-weight: 700;\r\n\t\tline-heig" +
                    "ht: 1em;\r\n\t\tmargin: 0 0 1em 0;\r\n\t}\r\n\r\n\t\th1 a, h2 a, h3 a, h4 a, h5 a, h6 a {\r\n\t\t" +
                    "\tcolor: inherit;\r\n\t\t\ttext-decoration: none;\r\n\t\t}\r\n\r\n\th1 {\r\n\t\tfont-size: 2.5em;\r\n" +
                    "\t\tline-height: 1.25em;\r\n\t}\r\n\r\n\th2 {\r\n\t\tfont-size: 1.75em;\r\n\t\tline-height: 1.5em;" +
                    "\r\n\t}\r\n\r\n\th3 {\r\n\t\tfont-size: 1.35em;\r\n\t\tline-height: 1.5em;\r\n\t}\r\n\r\n\th4 {\r\n\t\tfont-" +
                    "size: 1.1em;\r\n\t\tline-height: 1.5em;\r\n\t}\r\n\r\n\th5 {\r\n\t\tfont-size: 0.9em;\r\n\t\tline-he" +
                    "ight: 1.5em;\r\n\t}\r\n\r\n\th6 {\r\n\t\tfont-size: 0.7em;\r\n\t\tline-height: 1.5em;\r\n\t}\r\n\r\n\tsu" +
                    "b {\r\n\t\tfont-size: 0.8em;\r\n\t\tposition: relative;\r\n\t\ttop: 0.5em;\r\n\t}\r\n\r\n\tsup {\r\n\t\t" +
                    "font-size: 0.8em;\r\n\t\tposition: relative;\r\n\t\ttop: -0.5em;\r\n\t}\r\n\r\n\tblockquote {\r\n\t" +
                    "\tborder-left: solid 8px rgba(255, 255, 255, 0.35);\r\n\t\tfont-style: italic;\r\n\t\tmar" +
                    "gin: 0 0 2em 0;\r\n\t\tpadding: 0.5em 0 0.5em 2em;\r\n\t}\r\n\r\n\tcode {\r\n\t\tbackground: rgb" +
                    "a(255, 255, 255, 0.125);\r\n\t\tborder-radius: 6px;\r\n\t\tborder: solid 2px rgba(255, 2" +
                    "55, 255, 0.35);\r\n\t\tfont-family: \"Courier New\", monospace;\r\n\t\tfont-size: 0.9em;\r\n" +
                    "\t\tmargin: 0 0.25em;\r\n\t\tpadding: 0.25em 0.65em;\r\n\t}\r\n\r\n\tpre {\r\n\t\t-webkit-overflow" +
                    "-scrolling: touch;\r\n\t\tfont-family: \"Courier New\", monospace;\r\n\t\tfont-size: 0.9em" +
                    ";\r\n\t\tmargin: 0 0 2em 0;\r\n\t}\r\n\r\n\t\tpre code {\r\n\t\t\tdisplay: block;\r\n\t\t\tline-height:" +
                    " 1.75em;\r\n\t\t\tpadding: 1em 1.5em;\r\n\t\t\toverflow-x: auto;\r\n\t\t}\r\n\r\n\thr {\r\n\t\tborder: " +
                    "0;\r\n\t\tborder-bottom: solid 2px rgba(255, 255, 255, 0.35);\r\n\t\tmargin: 2em 0;\r\n\t}\r" +
                    "\n\r\n\t\thr.major {\r\n\t\t\tmargin: 3em 0;\r\n\t\t}\r\n\r\n/* Section/Article */\r\n\r\n\tsection.spe" +
                    "cial, article.special {\r\n\t\ttext-align: center;\r\n\t}\r\n\r\n\theader p {\r\n\t\tcolor: rgba" +
                    "(255, 255, 255, 0.5);\r\n\t\tposition: relative;\r\n\t\tmargin: 0 0 1.5em 0;\r\n\t}\r\n\r\n\thea" +
                    "der h2 + p {\r\n\t\tfont-size: 1.25em;\r\n\t\tmargin-top: -1em;\r\n\t\tline-height: 1.5em;\r\n" +
                    "\t}\r\n\r\n\theader h3 + p {\r\n\t\tfont-size: 1.1em;\r\n\t\tmargin-top: -0.8em;\r\n\t\tline-heigh" +
                    "t: 1.5em;\r\n\t}\r\n\r\n\theader h4 + p,\r\n\theader h5 + p,\r\n\theader h6 + p {\r\n\t\tfont-size" +
                    ": 0.9em;\r\n\t\tmargin-top: -0.6em;\r\n\t\tline-height: 1.5em;\r\n\t}\r\n\r\n\t@media screen and" +
                    " (max-width: 980px) {\r\n\r\n\t\theader br {\r\n\t\t\tdisplay: none;\r\n\t\t}\r\n\r\n\t}\r\n\r\n\t@media " +
                    "screen and (max-width: 736px) {\r\n\r\n\t\theader br {\r\n\t\t\tdisplay: inline;\r\n\t\t}\r\n\r\n\t}" +
                    "\r\n\r\n\t@media screen and (max-width: 480px) {\r\n\r\n\t\theader br {\r\n\t\t\tdisplay: none;\r" +
                    "\n\t\t}\r\n\r\n\t}\r\n\r\n/* Icon */\r\n\r\n\t.icon {\r\n\t\ttext-decoration: none;\r\n\t\tborder-bottom:" +
                    " none;\r\n\t\tposition: relative;\r\n\t}\r\n\r\n\t\t.icon:before {\r\n\t\t\t-moz-osx-font-smoothin" +
                    "g: grayscale;\r\n\t\t\t-webkit-font-smoothing: antialiased;\r\n\t\t\tfont-family: FontAwes" +
                    "ome;\r\n\t\t\tfont-style: normal;\r\n\t\t\tfont-weight: normal;\r\n\t\t\ttext-transform: none !" +
                    "important;\r\n\t\t}\r\n\r\n\t\t.icon > .label {\r\n\t\t\tdisplay: none;\r\n\t\t}\r\n\r\n/* List */\r\n\r\n\t" +
                    "ol {\r\n\t\tlist-style: decimal;\r\n\t\tmargin: 0 0 2em 0;\r\n\t\tpadding-left: 1.25em;\r\n\t}\r" +
                    "\n\r\n\t\tol li {\r\n\t\t\tpadding-left: 0.25em;\r\n\t\t}\r\n\r\n\tul {\r\n\t\tlist-style: disc;\r\n\t\tmar" +
                    "gin: 0 0 2em 0;\r\n\t\tpadding-left: 1em;\r\n\t}\r\n\r\n\t\tul li {\r\n\t\t\tpadding-left: 0.5em;\r" +
                    "\n\t\t}\r\n\r\n\t\tul.icons {\r\n\t\t\tcursor: default;\r\n\t\t\tlist-style: none;\r\n\t\t\tpadding-left" +
                    ": 0;\r\n\t\t}\r\n\r\n\t\t\tul.icons li {\r\n\t\t\t\tdisplay: inline-block;\r\n\t\t\t\tpadding: 0 1em 0 " +
                    "0;\r\n\t\t\t}\r\n\r\n\t\t\t\tul.icons li:last-child {\r\n\t\t\t\t\tpadding-right: 0;\r\n\t\t\t\t}\r\n\r\n\t\t\t\tu" +
                    "l.icons li .icon:before {\r\n\t\t\t\t\tfont-size: 1.25em;\r\n\t\t\t\t}\r\n\r\n\t\t\t\tul.icons li a {" +
                    "\r\n\t\t\t\t\tcolor: inherit;\r\n\t\t\t\t}\r\n\r\n/* Form */\r\n\r\n\tform {\r\n\t\tmargin: 0 0 2em 0;\r\n\t}" +
                    "\r\n\r\n\t\tform .message {\r\n\t\t\ttext-decoration: none;\r\n\t\t\t-moz-transition: opacity 0." +
                    "2s ease-in-out, -moz-transform 0.2s ease-in-out;\r\n\t\t\t-webkit-transition: opacity" +
                    " 0.2s ease-in-out, -webkit-transform 0.2s ease-in-out;\r\n\t\t\t-ms-transition: opaci" +
                    "ty 0.2s ease-in-out, -ms-transform 0.2s ease-in-out;\r\n\t\t\ttransition: opacity 0.2" +
                    "s ease-in-out, transform 0.2s ease-in-out;\r\n\t\t\t-moz-transform: scale(1.05);\r\n\t\t\t" +
                    "-webkit-transform: scale(1.05);\r\n\t\t\t-ms-transform: scale(1.05);\r\n\t\t\ttransform: s" +
                    "cale(1.05);\r\n\t\t\theight: 2.75em;\r\n\t\t\tline-height: 2.75em;\r\n\t\t\topacity: 0;\r\n\t\t}\r\n\r" +
                    "\n\t\t\tform .message:before {\r\n\t\t\t\t-moz-osx-font-smoothing: grayscale;\r\n\t\t\t\t-webkit" +
                    "-font-smoothing: antialiased;\r\n\t\t\t\tfont-family: FontAwesome;\r\n\t\t\t\tfont-style: no" +
                    "rmal;\r\n\t\t\t\tfont-weight: normal;\r\n\t\t\t\ttext-transform: none !important;\r\n\t\t\t}\r\n\r\n\t" +
                    "\t\tform .message:before {\r\n\t\t\t\tmargin-right: 0.5em;\r\n\t\t\t}\r\n\r\n\t\t\tform .message.vis" +
                    "ible {\r\n\t\t\t\t-moz-transform: scale(1);\r\n\t\t\t\t-webkit-transform: scale(1);\r\n\t\t\t\t-ms" +
                    "-transform: scale(1);\r\n\t\t\t\ttransform: scale(1);\r\n\t\t\t\topacity: 1;\r\n\t\t\t}\r\n\r\n\t\t\tfor" +
                    "m .message.success {\r\n\t\t\t\tcolor: #1cb495;\r\n\t\t\t}\r\n\r\n\t\t\t\tform .message.success:bef" +
                    "ore {\r\n\t\t\t\t\tcontent: \'\\f00c\';\r\n\t\t\t\t}\r\n\r\n\t\t\tform .message.failure {\r\n\t\t\t\tcolor: #" +
                    "ff2361;\r\n\t\t\t}\r\n\r\n\t\t\t\tform .message.failure:before {\r\n\t\t\t\t\tcontent: \'\\f119\';\r\n\t\t\t" +
                    "\t}\r\n\r\n\tlabel {\r\n\t\tcolor: #fff;\r\n\t\tdisplay: block;\r\n\t\tfont-size: 0.9em;\r\n\t\tfont-w" +
                    "eight: 700;\r\n\t\tmargin: 0 0 1em 0;\r\n\t}\r\n\r\n\t@-moz-keyframes focus {\r\n\t\t0% {\r\n\t\t\t-m" +
                    "oz-transform: scale(1);\r\n\t\t\t-webkit-transform: scale(1);\r\n\t\t\t-ms-transform: scal" +
                    "e(1);\r\n\t\t\ttransform: scale(1);\r\n\t\t}\r\n\r\n\t\t50% {\r\n\t\t\t-moz-transform: scale(1.025);" +
                    "\r\n\t\t\t-webkit-transform: scale(1.025);\r\n\t\t\t-ms-transform: scale(1.025);\r\n\t\t\ttrans" +
                    "form: scale(1.025);\r\n\t\t}\r\n\r\n\t\t100% {\r\n\t\t\t-moz-transform: scale(1);\r\n\t\t\t-webkit-t" +
                    "ransform: scale(1);\r\n\t\t\t-ms-transform: scale(1);\r\n\t\t\ttransform: scale(1);\r\n\t\t}\r\n" +
                    "\t}\r\n\r\n\t@-webkit-keyframes focus {\r\n\t\t0% {\r\n\t\t\t-moz-transform: scale(1);\r\n\t\t\t-web" +
                    "kit-transform: scale(1);\r\n\t\t\t-ms-transform: scale(1);\r\n\t\t\ttransform: scale(1);\r\n" +
                    "\t\t}\r\n\r\n\t\t50% {\r\n\t\t\t-moz-transform: scale(1.025);\r\n\t\t\t-webkit-transform: scale(1." +
                    "025);\r\n\t\t\t-ms-transform: scale(1.025);\r\n\t\t\ttransform: scale(1.025);\r\n\t\t}\r\n\r\n\t\t10" +
                    "0% {\r\n\t\t\t-moz-transform: scale(1);\r\n\t\t\t-webkit-transform: scale(1);\r\n\t\t\t-ms-tran" +
                    "sform: scale(1);\r\n\t\t\ttransform: scale(1);\r\n\t\t}\r\n\t}\r\n\r\n\t@-ms-keyframes focus {\r\n\t" +
                    "\t0% {\r\n\t\t\t-moz-transform: scale(1);\r\n\t\t\t-webkit-transform: scale(1);\r\n\t\t\t-ms-tra" +
                    "nsform: scale(1);\r\n\t\t\ttransform: scale(1);\r\n\t\t}\r\n\r\n\t\t50% {\r\n\t\t\t-moz-transform: s" +
                    "cale(1.025);\r\n\t\t\t-webkit-transform: scale(1.025);\r\n\t\t\t-ms-transform: scale(1.025" +
                    ");\r\n\t\t\ttransform: scale(1.025);\r\n\t\t}\r\n\r\n\t\t100% {\r\n\t\t\t-moz-transform: scale(1);\r\n" +
                    "\t\t\t-webkit-transform: scale(1);\r\n\t\t\t-ms-transform: scale(1);\r\n\t\t\ttransform: scal" +
                    "e(1);\r\n\t\t}\r\n\t}\r\n\r\n\t@keyframes focus {\r\n\t\t0% {\r\n\t\t\t-moz-transform: scale(1);\r\n\t\t\t" +
                    "-webkit-transform: scale(1);\r\n\t\t\t-ms-transform: scale(1);\r\n\t\t\ttransform: scale(1" +
                    ");\r\n\t\t}\r\n\r\n\t\t50% {\r\n\t\t\t-moz-transform: scale(1.025);\r\n\t\t\t-webkit-transform: scal" +
                    "e(1.025);\r\n\t\t\t-ms-transform: scale(1.025);\r\n\t\t\ttransform: scale(1.025);\r\n\t\t}\r\n\r\n" +
                    "\t\t100% {\r\n\t\t\t-moz-transform: scale(1);\r\n\t\t\t-webkit-transform: scale(1);\r\n\t\t\t-ms-" +
                    "transform: scale(1);\r\n\t\t\ttransform: scale(1);\r\n\t\t}\r\n\t}\r\n\r\n\tinput[type=\"text\"],\r\n" +
                    "\tinput[type=\"password\"],\r\n\tinput[type=\"email\"],\r\n\tselect,\r\n\ttextarea {\r\n\t\t-moz-a" +
                    "ppearance: none;\r\n\t\t-webkit-appearance: none;\r\n\t\t-ms-appearance: none;\r\n\t\tappear" +
                    "ance: none;\r\n\t\t-moz-transform: scale(1);\r\n\t\t-webkit-transform: scale(1);\r\n\t\t-ms-" +
                    "transform: scale(1);\r\n\t\ttransform: scale(1);\r\n\t\t-moz-transition: border-color 0." +
                    "2s ease, background-color 0.2s ease;\r\n\t\t-webkit-transition: border-color 0.2s ea" +
                    "se, background-color 0.2s ease;\r\n\t\t-ms-transition: border-color 0.2s ease, backg" +
                    "round-color 0.2s ease;\r\n\t\ttransition: border-color 0.2s ease, background-color 0" +
                    ".2s ease;\r\n\t\tbackground-color: transparent;\r\n\t\tborder-radius: 6px;\r\n\t\tborder: no" +
                    "ne;\r\n\t\tborder: solid 2px rgba(255, 255, 255, 0.35);\r\n\t\tcolor: inherit;\r\n\t\tdispla" +
                    "y: block;\r\n\t\toutline: 0;\r\n\t\tpadding: 0 1em;\r\n\t\ttext-decoration: none;\r\n\t\twidth: " +
                    "100%;\r\n\t}\r\n\r\n\t\tinput[type=\"text\"]:invalid,\r\n\t\tinput[type=\"password\"]:invalid,\r\n\t" +
                    "\tinput[type=\"email\"]:invalid,\r\n\t\tselect:invalid,\r\n\t\ttextarea:invalid {\r\n\t\t\tbox-s" +
                    "hadow: none;\r\n\t\t}\r\n\r\n\t\tinput[type=\"text\"]:focus,\r\n\t\tinput[type=\"password\"]:focus" +
                    ",\r\n\t\tinput[type=\"email\"]:focus,\r\n\t\tselect:focus,\r\n\t\ttextarea:focus {\r\n\t\t\t-moz-an" +
                    "imation: focus 0.1s;\r\n\t\t\t-webkit-animation: focus 0.1s;\r\n\t\t\t-ms-animation: focus" +
                    " 0.1s;\r\n\t\t\tanimation: focus 0.1s;\r\n\t\t\tbackground-color: rgba(255, 255, 255, 0.12" +
                    "5);\r\n\t\t\tborder-color: #1cb495;\r\n\t\t}\r\n\r\n\t.select-wrapper {\r\n\t\ttext-decoration: no" +
                    "ne;\r\n\t\tdisplay: block;\r\n\t\tposition: relative;\r\n\t}\r\n\r\n\t\t.select-wrapper:before {\r" +
                    "\n\t\t\t-moz-osx-font-smoothing: grayscale;\r\n\t\t\t-webkit-font-smoothing: antialiased;" +
                    "\r\n\t\t\tfont-family: FontAwesome;\r\n\t\t\tfont-style: normal;\r\n\t\t\tfont-weight: normal;\r" +
                    "\n\t\t\ttext-transform: none !important;\r\n\t\t}\r\n\r\n\t\t.select-wrapper:before {\r\n\t\t\tcolo" +
                    "r: rgba(255, 255, 255, 0.35);\r\n\t\t\tcontent: \'\\f078\';\r\n\t\t\tdisplay: block;\r\n\t\t\theig" +
                    "ht: 2.75em;\r\n\t\t\tline-height: 2.75em;\r\n\t\t\tpointer-events: none;\r\n\t\t\tposition: abs" +
                    "olute;\r\n\t\t\tright: 0;\r\n\t\t\ttext-align: center;\r\n\t\t\ttop: 0;\r\n\t\t\twidth: 2.75em;\r\n\t\t}" +
                    "\r\n\r\n\t\t.select-wrapper select::-ms-expand {\r\n\t\t\tdisplay: none;\r\n\t\t}\r\n\r\n\tinput[typ" +
                    "e=\"text\"],\r\n\tinput[type=\"password\"],\r\n\tinput[type=\"email\"],\r\n\tselect {\r\n\t\theight" +
                    ": 2.75em;\r\n\t}\r\n\r\n\ttextarea {\r\n\t\tpadding: 0.75em 1em;\r\n\t}\r\n\r\n\tinput[type=\"checkbo" +
                    "x\"],\r\n\tinput[type=\"radio\"] {\r\n\t\t-moz-appearance: none;\r\n\t\t-webkit-appearance: no" +
                    "ne;\r\n\t\t-ms-appearance: none;\r\n\t\tappearance: none;\r\n\t\tdisplay: block;\r\n\t\tfloat: l" +
                    "eft;\r\n\t\tmargin-right: -2em;\r\n\t\topacity: 0;\r\n\t\twidth: 1em;\r\n\t\tz-index: -1;\r\n\t}\r\n\r" +
                    "\n\t\tinput[type=\"checkbox\"] + label,\r\n\t\tinput[type=\"radio\"] + label {\r\n\t\t\ttext-dec" +
                    "oration: none;\r\n\t\t\tcolor: rgba(255, 255, 255, 0.75);\r\n\t\t\tcursor: pointer;\r\n\t\t\tdi" +
                    "splay: inline-block;\r\n\t\t\tfont-size: 1em;\r\n\t\t\tfont-weight: 400;\r\n\t\t\tpadding-left:" +
                    " 2.4em;\r\n\t\t\tpadding-right: 0.75em;\r\n\t\t\tposition: relative;\r\n\t\t}\r\n\r\n\t\t\tinput[type" +
                    "=\"checkbox\"] + label:before,\r\n\t\t\tinput[type=\"radio\"] + label:before {\r\n\t\t\t\t-moz-" +
                    "osx-font-smoothing: grayscale;\r\n\t\t\t\t-webkit-font-smoothing: antialiased;\r\n\t\t\t\tfo" +
                    "nt-family: FontAwesome;\r\n\t\t\t\tfont-style: normal;\r\n\t\t\t\tfont-weight: normal;\r\n\t\t\t\t" +
                    "text-transform: none !important;\r\n\t\t\t}\r\n\r\n\t\t\tinput[type=\"checkbox\"] + label:befo" +
                    "re,\r\n\t\t\tinput[type=\"radio\"] + label:before {\r\n\t\t\t\tbackground: rgba(255, 255, 255" +
                    ", 0.125);\r\n\t\t\t\tborder-radius: 6px;\r\n\t\t\t\tborder: solid 2px rgba(255, 255, 255, 0." +
                    "35);\r\n\t\t\t\tcontent: \'\';\r\n\t\t\t\tdisplay: inline-block;\r\n\t\t\t\theight: 1.65em;\r\n\t\t\t\tlef" +
                    "t: 0;\r\n\t\t\t\tline-height: 1.58125em;\r\n\t\t\t\tposition: absolute;\r\n\t\t\t\ttext-align: cen" +
                    "ter;\r\n\t\t\t\ttop: 0;\r\n\t\t\t\twidth: 1.65em;\r\n\t\t\t}\r\n\r\n\t\tinput[type=\"checkbox\"]:checked " +
                    "+ label:before,\r\n\t\tinput[type=\"radio\"]:checked + label:before {\r\n\t\t\tbackground: " +
                    "#1cb495;\r\n\t\t\tborder-color: #1cb495;\r\n\t\t\tcolor: #ffffff;\r\n\t\t\tcontent: \'\\f00c\';\r\n\t" +
                    "\t}\r\n\r\n\t\tinput[type=\"checkbox\"]:focus + label:before,\r\n\t\tinput[type=\"radio\"]:focu" +
                    "s + label:before {\r\n\t\t\tborder-color: #1cb495;\r\n\t\t\tbox-shadow: 0 0 0 2px #1cb495;" +
                    "\r\n\t\t}\r\n\r\n\tinput[type=\"checkbox\"] + label:before {\r\n\t\tborder-radius: 6px;\r\n\t}\r\n\r\n" +
                    "\tinput[type=\"radio\"] + label:before {\r\n\t\tborder-radius: 100%;\r\n\t}\r\n\r\n\t::-webkit-" +
                    "input-placeholder {\r\n\t\tcolor: rgba(255, 255, 255, 0.5) !important;\r\n\t\topacity: 1" +
                    ".0;\r\n\t}\r\n\r\n\t:-moz-placeholder {\r\n\t\tcolor: rgba(255, 255, 255, 0.5) !important;\r\n" +
                    "\t\topacity: 1.0;\r\n\t}\r\n\r\n\t::-moz-placeholder {\r\n\t\tcolor: rgba(255, 255, 255, 0.5) " +
                    "!important;\r\n\t\topacity: 1.0;\r\n\t}\r\n\r\n\t:-ms-input-placeholder {\r\n\t\tcolor: rgba(255" +
                    ", 255, 255, 0.5) !important;\r\n\t\topacity: 1.0;\r\n\t}\r\n\r\n\t.formerize-placeholder {\r\n" +
                    "\t\tcolor: rgba(255, 255, 255, 0.5) !important;\r\n\t\topacity: 1.0;\r\n\t}\r\n\r\n/* Button " +
                    "*/\r\n\r\n\tinput[type=\"submit\"],\r\n\tinput[type=\"reset\"],\r\n\tinput[type=\"button\"],\r\n\tbu" +
                    "tton,\r\n\t.button {\r\n\t\t-moz-appearance: none;\r\n\t\t-webkit-appearance: none;\r\n\t\t-ms-" +
                    "appearance: none;\r\n\t\tappearance: none;\r\n\t\t-moz-transition: background-color 0.2s" +
                    " ease-in-out, color 0.2s ease-in-out, opacity 0.2s ease-in-out;\r\n\t\t-webkit-trans" +
                    "ition: background-color 0.2s ease-in-out, color 0.2s ease-in-out, opacity 0.2s e" +
                    "ase-in-out;\r\n\t\t-ms-transition: background-color 0.2s ease-in-out, color 0.2s eas" +
                    "e-in-out, opacity 0.2s ease-in-out;\r\n\t\ttransition: background-color 0.2s ease-in" +
                    "-out, color 0.2s ease-in-out, opacity 0.2s ease-in-out;\r\n\t\tbackground-color: #1c" +
                    "b495;\r\n\t\tborder-radius: 6px;\r\n\t\tborder: 0;\r\n\t\tcolor: #ffffff !important;\r\n\t\tcurs" +
                    "or: pointer;\r\n\t\tdisplay: inline-block;\r\n\t\tfont-weight: 700;\r\n\t\theight: 2.75em;\r\n" +
                    "\t\tline-height: 2.75em;\r\n\t\tpadding: 0 1.125em;\r\n\t\ttext-align: center;\r\n\t\ttext-dec" +
                    "oration: none;\r\n\t\twhite-space: nowrap;\r\n\t}\r\n\r\n\t\tinput[type=\"submit\"]:hover,\r\n\t\ti" +
                    "nput[type=\"reset\"]:hover,\r\n\t\tinput[type=\"button\"]:hover,\r\n\t\tbutton:hover,\r\n\t\t.bu" +
                    "tton:hover {\r\n\t\t\tbackground-color: #1fcaa7;\r\n\t\t}\r\n\r\n\t\tinput[type=\"submit\"]:activ" +
                    "e,\r\n\t\tinput[type=\"reset\"]:active,\r\n\t\tinput[type=\"button\"]:active,\r\n\t\tbutton:acti" +
                    "ve,\r\n\t\t.button:active {\r\n\t\t\tbackground-color: #199e83;\r\n\t\t}\r\n\r\n\t\tinput[type=\"sub" +
                    "mit\"].disabled, input[type=\"submit\"]:disabled,\r\n\t\tinput[type=\"reset\"].disabled,\r" +
                    "\n\t\tinput[type=\"reset\"]:disabled,\r\n\t\tinput[type=\"button\"].disabled,\r\n\t\tinput[type" +
                    "=\"button\"]:disabled,\r\n\t\tbutton.disabled,\r\n\t\tbutton:disabled,\r\n\t\t.button.disabled" +
                    ",\r\n\t\t.button:disabled {\r\n\t\t\topacity: 0.5;\r\n\t\t}\r\n\r\n\t\t@media screen and (max-width" +
                    ": 480px) {\r\n\r\n\t\t\tinput[type=\"submit\"],\r\n\t\t\tinput[type=\"reset\"],\r\n\t\t\tinput[type=\"" +
                    "button\"],\r\n\t\t\tbutton,\r\n\t\t\t.button {\r\n\t\t\t\tpadding: 0;\r\n\t\t\t}\r\n\r\n\t\t}\r\n\r\n/* Header *" +
                    "/\r\n\r\n\t#header h1 {\r\n\t\tfont-size: 3.25em;\r\n\t\tmargin: 0 0 0.55em 0;\r\n\t}\r\n\r\n\t#heade" +
                    "r p {\r\n\t\tfont-size: 1.35em;\r\n\t\tline-height: 1.65em;\r\n\t}\r\n\r\n\t#header a {\r\n\t\tcolor" +
                    ": inherit;\r\n\t}\r\n\r\n\t@media screen and (max-width: 736px) {\r\n\r\n\t\t#header h1 {\r\n\t\t\t" +
                    "font-size: 2em;\r\n\t\t}\r\n\r\n\t\t#header p {\r\n\t\t\tfont-size: 1em;\r\n\t\t}\r\n\r\n\t}\r\n\r\n\t@media " +
                    "screen and (max-width: 480px) {\r\n\r\n\t\t#header {\r\n\t\t\tmargin: 0 0 1em 0;\r\n\t\t}\r\n\r\n\t}" +
                    "\r\n\r\n/* Signup Form */\r\n\r\n\t#signup-form {\r\n\t\tdisplay: -moz-flex;\r\n\t\tdisplay: -web" +
                    "kit-flex;\r\n\t\tdisplay: -ms-flex;\r\n\t\tdisplay: flex;\r\n\t\tposition: relative;\r\n\t}\r\n\r\n" +
                    "\t\t#signup-form input[type=\"text\"],\r\n\t\t#signup-form input[type=\"password\"],\r\n\t\t#s" +
                    "ignup-form input[type=\"email\"] {\r\n\t\t\twidth: 18em;\r\n\t\t}\r\n\r\n\t\t#signup-form > * {\r\n" +
                    "\t\t\tmargin: 0 0 0 1em;\r\n\t\t}\r\n\r\n\t\t#signup-form > :first-child {\r\n\t\t\tmargin: 0 0 0 " +
                    "0;\r\n\t\t}\r\n\r\n\t\t@media screen and (max-width: 480px) {\r\n\r\n\t\t\t#signup-form {\r\n\t\t\t\t-m" +
                    "oz-flex-direction: column;\r\n\t\t\t\t-webkit-flex-direction: column;\r\n\t\t\t\t-ms-flex-di" +
                    "rection: column;\r\n\t\t\t\tflex-direction: column;\r\n\t\t\t}\r\n\r\n\t\t\t\t#signup-form input[ty" +
                    "pe=\"type\"],\r\n\t\t\t\t#signup-form input[type=\"password\"],\r\n\t\t\t\t#signup-form input[ty" +
                    "pe=\"email\"] {\r\n\t\t\t\t\twidth: 100%;\r\n\t\t\t\t}\r\n\r\n\t\t\t\t#signup-form > * {\r\n\t\t\t\t\tmargin: " +
                    "1.25em 0 0 0;\r\n\t\t\t\t}\r\n\r\n\t\t\t\t#signup-form .message {\r\n\t\t\t\t\tbottom: -1.5em;\r\n\t\t\t\t\t" +
                    "font-size: 0.9em;\r\n\t\t\t\t\theight: 1em;\r\n\t\t\t\t\tleft: 0;\r\n\t\t\t\t\tline-height: inherit;\r" +
                    "\n\t\t\t\t\tmargin-top: 0;\r\n\t\t\t\t\tposition: absolute;\r\n\t\t\t\t}\r\n\r\n\t\t}\r\n\r\n/* Footer */\r\n\r\n" +
                    "\t#footer {\r\n\t\t-moz-transition: opacity 0.5s ease-in-out;\r\n\t\t-webkit-transition: " +
                    "opacity 0.5s ease-in-out;\r\n\t\t-ms-transition: opacity 0.5s ease-in-out;\r\n\t\ttransi" +
                    "tion: opacity 0.5s ease-in-out;\r\n\t\tbottom: 4em;\r\n\t\tcolor: rgba(255, 255, 255, 0." +
                    "5);\r\n\t\tleft: 4em;\r\n\t\topacity: 0.5;\r\n\t\tposition: absolute;\r\n\t}\r\n\r\n\t\t#footer .icon" +
                    "s {\r\n\t\t\tmargin: 0 0 0.5em 0;\r\n\t\t}\r\n\r\n\t\t#footer .copyright {\r\n\t\t\tfont-size: 0.8em" +
                    ";\r\n\t\t\tlist-style: none;\r\n\t\t\tpadding: 0;\r\n\t\t}\r\n\r\n\t\t\t#footer .copyright li {\r\n\t\t\t\t" +
                    "border-left: solid 1px rgba(255, 255, 255, 0.25);\r\n\t\t\t\tdisplay: inline-block;\r\n\t" +
                    "\t\t\tline-height: 1em;\r\n\t\t\t\tmargin: 0 0 0 0.75em;\r\n\t\t\t\tpadding: 0 0 0 0.75em;\r\n\t\t\t" +
                    "}\r\n\r\n\t\t\t\t#footer .copyright li:first-child {\r\n\t\t\t\t\tborder-left: 0;\r\n\t\t\t\t\tmargin-" +
                    "left: 0;\r\n\t\t\t\t\tpadding-left: 0;\r\n\t\t\t\t}\r\n\r\n\t\t\t#footer .copyright a {\r\n\t\t\t\tcolor: " +
                    "inherit;\r\n\t\t\t}\r\n\r\n\t\t#footer:hover {\r\n\t\t\topacity: 1;\r\n\t\t}\r\n\r\n\t\t#footer > :last-ch" +
                    "ild {\r\n\t\t\tmargin-bottom: 0;\r\n\t\t}\r\n\r\n\t\t@media screen and (max-width: 1680px) {\r\n\r" +
                    "\n\t\t\t#footer {\r\n\t\t\t\tbottom: 3.5em;\r\n\t\t\t\tleft: 3.5em;\r\n\t\t\t}\r\n\r\n\t\t}\r\n\r\n\t\t@media scr" +
                    "een and (max-width: 736px) {\r\n\r\n\t\t\t#footer {\r\n\t\t\t\tbottom: 2em;\r\n\t\t\t\tleft: 2em;\r\n" +
                    "\t\t\t}\r\n\r\n\t\t}\r\n\r\n\t\t@media screen and (max-width: 360px) {\r\n\r\n\t\t\t#footer {\r\n\t\t\t\tbot" +
                    "tom: 1.25em;\r\n\t\t\t\tleft: 1.25em;\r\n\t\t\t}\r\n\r\n\t\t}\r\n\r\n\t\t@media screen and (max-height:" +
                    " 640px) {\r\n\r\n\t\t\t#footer {\r\n\t\t\t\tbottom: auto;\r\n\t\t\t\tleft: auto;\r\n\t\t\t\tmargin: 1em 0" +
                    " 0 0;\r\n\t\t\t\tposition: relative;\r\n\t\t\t}\r\n\r\n\t\t}\r\n\t\t</style>\r\n</head>\r\n<body>\r\n\r\n    " +
                    "<!-- Header -->\r\n    <header id=\"header\">\r\n        <h1>");
            
            #line 1214 "C:\Users\ucrm4\Source\Repos\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Manifest.ApplicationName));
            
            #line default
            #line hidden
            this.Write("</h1>\r\n        <h2>");
            
            #line 1215 "C:\Users\ucrm4\Source\Repos\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Manifest.AuthorName));
            
            #line default
            #line hidden
            this.Write("</h2>\r\n        <h3>");
            
            #line 1216 "C:\Users\ucrm4\Source\Repos\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Manifest.PublisherName));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n        <p>\r\n            ");
            
            #line 1218 "C:\Users\ucrm4\Source\Repos\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Manifest.SuiteName));
            
            #line default
            #line hidden
            this.Write("\r\n        </p>\r\n        <p>\r\n            ");
            
            #line 1221 "C:\Users\ucrm4\Source\Repos\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Manifest.Summary));
            
            #line default
            #line hidden
            this.Write("\r\n        </p>\r\n    </header>\r\n    <p>");
            
            #line 1224 "C:\Users\ucrm4\Source\Repos\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Manifest.Description));
            
            #line default
            #line hidden
            this.Write("</p>\r\n    <!-- Signup Form -->\r\n    <form id=\"signup-form\" method=\"post\" action=\"" +
                    "#\">\r\n        <input type=\"text\" disabled placeholder=\"Requires .NET Framework ");
            
            #line 1227 "C:\Users\ucrm4\Source\Repos\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Manifest.FrameworkVersion));
            
            #line default
            #line hidden
            this.Write("\" ></input>\r\n        <a class=\"button btn-lg\" href=\"");
            
            #line 1228 "C:\Users\ucrm4\Source\Repos\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AppLauncher.Name));
            
            #line default
            #line hidden
            this.Write("\">Launch</a>\r\n        <a class=\"button btn-lg\" href=\"setup.exe\">Install</a>\r\n    " +
                    "</form>\r\n    <!-- Footer -->\r\n    <footer id=\"footer\">\r\n        <ul class=\"copyr" +
                    "ight\">\r\n            <li>\r\n\t\t\t");
            
            #line 1235 "C:\Users\ucrm4\Source\Repos\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
 
				if(!string.IsNullOrWhiteSpace(Model.Manifest.Copyright))
				{
				
            
            #line default
            #line hidden
            this.Write("\t\t\t\t© ");
            
            #line 1239 "C:\Users\ucrm4\Source\Repos\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Manifest.Copyright));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t");
            
            #line 1240 "C:\Users\ucrm4\Source\Repos\ClickTwice\src\ClickTwice.Publisher.Core\Resources\LaunchPage.tt"

				}
				
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t</li>\r\n            <li><a href=\"http://html5up.net\">HTML5 UP</a></li>\r\n     " +
                    "       <li><a href=\"https://bitbucket.org/agc93/clicktwice\" target=\"_blank\">Clic" +
                    "kTwice</a></li>\r\n        </ul>\r\n    </footer>\r\n\r\n    <!-- Scripts -->\r\n    <!--[" +
                    "if lte IE 8]><script src=\"assets/js/ie/respond.min.js\"></script><![endif]-->\r\n<!" +
                    "-- <script src=\"assets/js/main.js\"></script> -->\r\n<script type=\"text/javascript\"" +
                    ">\r\n/*\r\n\tEventually by HTML5 UP\r\n\thtml5up.net | @n33co\r\n\tFree for personal and co" +
                    "mmercial use under the CCA 3.0 license (html5up.net/license)\r\n*/\r\n\r\n(function() " +
                    "{\r\n\r\n\t\"use strict\";\r\n\r\n\t// Methods/polyfills.\r\n\r\n\t\t// classList | (c) @remy | gi" +
                    "thub.com/remy/polyfills | rem.mit-license.org\r\n\t\t\t!function(){function t(t){this" +
                    ".el=t;for(var n=t.className.replace(/^\\s+|\\s+$/g,\"\").split(/\\s+/),i=0;i<n.length" +
                    ";i++)e.call(this,n[i])}function n(t,n,i){Object.defineProperty?Object.defineProp" +
                    "erty(t,n,{get:i}):t.__defineGetter__(n,i)}if(!(\"undefined\"==typeof window.Elemen" +
                    "t||\"classList\"in document.documentElement)){var i=Array.prototype,e=i.push,s=i.s" +
                    "plice,o=i.join;t.prototype={add:function(t){this.contains(t)||(e.call(this,t),th" +
                    "is.el.className=this.toString())},contains:function(t){return-1!=this.el.classNa" +
                    "me.indexOf(t)},item:function(t){return this[t]||null},remove:function(t){if(this" +
                    ".contains(t)){for(var n=0;n<this.length&&this[n]!=t;n++);s.call(this,n,1),this.e" +
                    "l.className=this.toString()}},toString:function(){return o.call(this,\" \")},toggl" +
                    "e:function(t){return this.contains(t)?this.remove(t):this.add(t),this.contains(t" +
                    ")}},window.DOMTokenList=t,n(Element.prototype,\"classList\",function(){return new " +
                    "t(this)})}}();\r\n\r\n\t\t// canUse\r\n\t\t\twindow.canUse=function(p){if(!window._canUse)w" +
                    "indow._canUse=document.createElement(\"div\");var e=window._canUse.style,up=p.char" +
                    "At(0).toUpperCase()+p.slice(1);return p in e||\"Moz\"+up in e||\"Webkit\"+up in e||\"" +
                    "O\"+up in e||\"ms\"+up in e};\r\n\r\n\t\t// window.addEventListener\r\n\t\t\t(function(){if(\"a" +
                    "ddEventListener\"in window)return;window.addEventListener=function(type,f){window" +
                    ".attachEvent(\"on\"+type,f)}})();\r\n\r\n\t// Vars.\r\n\t\tvar\t$body = document.querySelect" +
                    "or(\'body\');\r\n\r\n\t// Disable animations/transitions until everything\'s loaded.\r\n\t\t" +
                    "$body.classList.add(\'is-loading\');\r\n\r\n\t\twindow.addEventListener(\'load\', function" +
                    "() {\r\n\t\t\twindow.setTimeout(function() {\r\n\t\t\t\t$body.classList.remove(\'is-loading\'" +
                    ");\r\n\t\t\t}, 100);\r\n\t\t});\r\n\r\n\t// Slideshow Background.\r\n\t\t(function() {\r\n\r\n\t\t\t// Se" +
                    "ttings.\r\n\t\t\t\tvar settings = {\r\n\r\n\t\t\t\t\t// Images (in the format of \'url\': \'alignm" +
                    "ent\').\r\n\t\t\t\t\t\timages: {\r\n\t\t\t\t\t\t\t\'http://i.imgur.com/bfesoBp.jpg\': \'center\',\r\n\t\t\t" +
                    "\t\t\t\t\'http://i.imgur.com/bfesoBp.jpg\': \'center\'\r\n\t\t\t\t\t\t},\r\n\r\n\t\t\t\t\t// Delay.\r\n\t\t\t\t" +
                    "\t\tdelay: 6000\r\n\r\n\t\t\t\t};\r\n\r\n\t\t\t// Vars.\r\n\t\t\t\tvar\tpos = 0, lastPos = 0,\r\n\t\t\t\t\t$wra" +
                    "pper, $bgs = [], $bg,\r\n\t\t\t\t\tk, v;\r\n\r\n\t\t\t// Create BG wrapper, BGs.\r\n\t\t\t\t$wrapper" +
                    " = document.createElement(\'div\');\r\n\t\t\t\t\t$wrapper.id = \'bg\';\r\n\t\t\t\t\t$body.appendCh" +
                    "ild($wrapper);\r\n\r\n\t\t\t\tfor (k in settings.images) {\r\n\r\n\t\t\t\t\t// Create BG.\r\n\t\t\t\t\t\t" +
                    "$bg = document.createElement(\'div\');\r\n\t\t\t\t\t\t\t$bg.style.backgroundImage = \'url(\"\'" +
                    " + k + \'\")\';\r\n\t\t\t\t\t\t\t$bg.style.backgroundPosition = settings.images[k];\r\n\t\t\t\t\t\t\t" +
                    "$wrapper.appendChild($bg);\r\n\r\n\t\t\t\t\t// Add it to array.\r\n\t\t\t\t\t\t$bgs.push($bg);\r\n\r" +
                    "\n\t\t\t\t}\r\n\r\n\t\t\t// Main loop.\r\n\t\t\t\t$bgs[pos].classList.add(\'visible\');\r\n\t\t\t\t$bgs[po" +
                    "s].classList.add(\'top\');\r\n\r\n\t\t\t\t// Bail if we only have a single BG or the clien" +
                    "t doesn\'t support transitions.\r\n\t\t\t\t\tif ($bgs.length == 1\r\n\t\t\t\t\t||\t!canUse(\'tran" +
                    "sition\'))\r\n\t\t\t\t\t\treturn;\r\n\r\n\t\t\t\twindow.setInterval(function() {\r\n\r\n\t\t\t\t\tlastPos " +
                    "= pos;\r\n\t\t\t\t\tpos++;\r\n\r\n\t\t\t\t\t// Wrap to beginning if necessary.\r\n\t\t\t\t\t\tif (pos >=" +
                    " $bgs.length)\r\n\t\t\t\t\t\t\tpos = 0;\r\n\r\n\t\t\t\t\t// Swap top images.\r\n\t\t\t\t\t\t$bgs[lastPos]." +
                    "classList.remove(\'top\');\r\n\t\t\t\t\t\t$bgs[pos].classList.add(\'visible\');\r\n\t\t\t\t\t\t$bgs[" +
                    "pos].classList.add(\'top\');\r\n\r\n\t\t\t\t\t// Hide last image after a short delay.\r\n\t\t\t\t" +
                    "\t\twindow.setTimeout(function() {\r\n\t\t\t\t\t\t\t$bgs[lastPos].classList.remove(\'visible" +
                    "\');\r\n\t\t\t\t\t\t}, settings.delay / 2);\r\n\r\n\t\t\t\t}, settings.delay);\r\n\r\n\t\t})();\r\n\r\n\t// " +
                    "Signup Form.\r\n\t\t(function() {\r\n\r\n\t\t\t// Vars.\r\n\t\t\t\tvar $form = document.querySele" +
                    "ctorAll(\'#signup-form\')[0],\r\n\t\t\t\t\t$submit = document.querySelectorAll(\'#signup-f" +
                    "orm input[type=\"submit\"]\')[0],\r\n\t\t\t\t\t$message;\r\n\r\n\t\t\t// Bail if addEventListener" +
                    " isn\'t supported.\r\n\t\t\t\tif (!(\'addEventListener\' in $form))\r\n\t\t\t\t\treturn;\r\n\r\n\t\t\t/" +
                    "/ Message.\r\n\t\t\t\t$message = document.createElement(\'span\');\r\n\t\t\t\t\t$message.classL" +
                    "ist.add(\'message\');\r\n\t\t\t\t\t$form.appendChild($message);\r\n\r\n\t\t\t\t$message._show = f" +
                    "unction(type, text) {\r\n\r\n\t\t\t\t\t$message.innerHTML = text;\r\n\t\t\t\t\t$message.classLis" +
                    "t.add(type);\r\n\t\t\t\t\t$message.classList.add(\'visible\');\r\n\r\n\t\t\t\t\twindow.setTimeout(" +
                    "function() {\r\n\t\t\t\t\t\t$message._hide();\r\n\t\t\t\t\t}, 3000);\r\n\r\n\t\t\t\t};\r\n\r\n\t\t\t\t$message." +
                    "_hide = function() {\r\n\t\t\t\t\t$message.classList.remove(\'visible\');\r\n\t\t\t\t};\r\n\r\n\t\t\t/" +
                    "/ Events.\r\n\t\t\t// Note: If you\'re *not* using AJAX, get rid of this event listene" +
                    "r.\r\n\t\t\t\t$form.addEventListener(\'submit\', function(event) {\r\n\r\n\t\t\t\t\tevent.stopPro" +
                    "pagation();\r\n\t\t\t\t\tevent.preventDefault();\r\n\r\n\t\t\t\t\t// Hide message.\r\n\t\t\t\t\t\t$messa" +
                    "ge._hide();\r\n\r\n\t\t\t\t\t// Disable submit.\r\n\t\t\t\t\t\t$submit.disabled = true;\r\n\r\n\t\t\t\t\t/" +
                    "/ Process form.\r\n\t\t\t\t\t// Note: Doesn\'t actually do anything yet (other than repo" +
                    "rt back with a \"thank you\"),\r\n\t\t\t\t\t// but there\'s enough here to piece together " +
                    "a working AJAX submission call that does.\r\n\t\t\t\t\t\twindow.setTimeout(function() {\r" +
                    "\n\r\n\t\t\t\t\t\t\t// Reset form.\r\n\t\t\t\t\t\t\t\t$form.reset();\r\n\r\n\t\t\t\t\t\t\t// Enable submit.\r\n\t\t" +
                    "\t\t\t\t\t\t$submit.disabled = false;\r\n\r\n\t\t\t\t\t\t\t// Show message.\r\n\t\t\t\t\t\t\t\t$message._sh" +
                    "ow(\'success\', \'Thank you!\');\r\n\t\t\t\t\t\t\t\t//$message._show(\'failure\', \'Something wen" +
                    "t wrong. Please try again.\');\r\n\r\n\t\t\t\t\t\t}, 750);\r\n\r\n\t\t\t\t});\r\n\r\n\t\t})();\r\n\r\n})();\r\n" +
                    "</script>\r\n\r\n</body>\r\n</html>\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class LaunchPageBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
